/**
 * This class is generated by jOOQ
 */
package mineplex.database;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Account extends org.jooq.impl.SchemaImpl implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 625106486;

	/**
	 * The reference instance of <code>Account</code>
	 */
	public static final Account Account = new Account();

	/**
	 * No further instances allowed
	 */
	private Account() {
		super("Account");
	}

	@Override
	public final java.util.List<org.jooq.Table<?>> getTables() {
		java.util.List result = new java.util.ArrayList();
		result.addAll(getTables0());
		return result;
	}

	private final java.util.List<org.jooq.Table<?>> getTables0() {
		return java.util.Arrays.<org.jooq.Table<?>>asList(
			mineplex.database.tables.AccountClan.accountClan,
			mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions,
			mineplex.database.tables.AccountFriend.accountFriend,
			mineplex.database.tables.AccountGemTransactions.accountGemTransactions,
			mineplex.database.tables.AccountIgnore.accountIgnore,
			mineplex.database.tables.AccountInventory.accountInventory,
			mineplex.database.tables.AccountPolls.accountPolls,
			mineplex.database.tables.AccountPreferences.accountPreferences,
			mineplex.database.tables.Accounts.accounts,
			mineplex.database.tables.AccountStat.accountStat,
			mineplex.database.tables.AccountStats.accountStats,
			mineplex.database.tables.AccountTasks.accountTasks,
			mineplex.database.tables.AccountTransactions.accountTransactions,
			mineplex.database.tables.ActiveTournaments.activeTournaments,
			mineplex.database.tables.Bonus.bonus,
			mineplex.database.tables.ClanAlliances.clanAlliances,
			mineplex.database.tables.ClanEnemies.clanEnemies,
			mineplex.database.tables.ClanMember.clanMember,
			mineplex.database.tables.Clans.clans,
			mineplex.database.tables.ClanServer.clanServer,
			mineplex.database.tables.ClanShopItem.clanShopItem,
			mineplex.database.tables.ClanTerritory.clanTerritory,
			mineplex.database.tables.EloRating.eloRating,
			mineplex.database.tables.FieldBlock.fieldBlock,
			mineplex.database.tables.FieldMonster.fieldMonster,
			mineplex.database.tables.FieldOre.fieldOre,
			mineplex.database.tables.ItemCategories.itemCategories,
			mineplex.database.tables.Items.items,
			mineplex.database.tables.Mail.mail,
			mineplex.database.tables.Mailbox.mailbox,
			mineplex.database.tables.Npcs.npcs,
			mineplex.database.tables.PlayerMap.playerMap,
			mineplex.database.tables.Polls.polls,
			mineplex.database.tables.RankBenefits.rankBenefits,
			mineplex.database.tables.ServerPassword.serverPassword,
			mineplex.database.tables.Spawns.spawns,
			mineplex.database.tables.StatEvents.statEvents,
			mineplex.database.tables.Stats.stats,
			mineplex.database.tables.StatTypes.statTypes,
			mineplex.database.tables.Tasks.tasks,
			mineplex.database.tables.TournamentLB.TournamentLB,
			mineplex.database.tables.Transactions.transactions);
	}
}
