/**
 * This class is generated by jOOQ
 */
package mineplex.database;

/**
 * A class modelling foreign key relationships between tables of the <code>Account</code> 
 * schema
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Keys {

	// -------------------------------------------------------------------------
	// IDENTITY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.Identity<mineplex.database.tables.records.AccountClanRecord, java.lang.Integer> IDENTITY_accountClan = Identities0.IDENTITY_accountClan;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountCoinTransactionsRecord, java.lang.Integer> IDENTITY_accountCoinTransactions = Identities0.IDENTITY_accountCoinTransactions;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountFriendRecord, java.lang.Integer> IDENTITY_accountFriend = Identities0.IDENTITY_accountFriend;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountGemTransactionsRecord, java.lang.Integer> IDENTITY_accountGemTransactions = Identities0.IDENTITY_accountGemTransactions;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountIgnoreRecord, java.lang.Integer> IDENTITY_accountIgnore = Identities0.IDENTITY_accountIgnore;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountInventoryRecord, java.lang.Integer> IDENTITY_accountInventory = Identities0.IDENTITY_accountInventory;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountPollsRecord, java.lang.Integer> IDENTITY_accountPolls = Identities0.IDENTITY_accountPolls;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountPreferencesRecord, java.lang.Integer> IDENTITY_accountPreferences = Identities0.IDENTITY_accountPreferences;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountsRecord, java.lang.Integer> IDENTITY_accounts = Identities0.IDENTITY_accounts;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountStatsRecord, java.lang.Integer> IDENTITY_accountStats = Identities0.IDENTITY_accountStats;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountTasksRecord, java.lang.Integer> IDENTITY_accountTasks = Identities0.IDENTITY_accountTasks;
	public static final org.jooq.Identity<mineplex.database.tables.records.AccountTransactionsRecord, java.lang.Integer> IDENTITY_accountTransactions = Identities0.IDENTITY_accountTransactions;
	public static final org.jooq.Identity<mineplex.database.tables.records.BonusRecord, java.lang.Integer> IDENTITY_bonus = Identities0.IDENTITY_bonus;
	public static final org.jooq.Identity<mineplex.database.tables.records.ClanAlliancesRecord, java.lang.Integer> IDENTITY_clanAlliances = Identities0.IDENTITY_clanAlliances;
	public static final org.jooq.Identity<mineplex.database.tables.records.ClanEnemiesRecord, java.lang.Integer> IDENTITY_clanEnemies = Identities0.IDENTITY_clanEnemies;
	public static final org.jooq.Identity<mineplex.database.tables.records.ClansRecord, java.lang.Integer> IDENTITY_clans = Identities0.IDENTITY_clans;
	public static final org.jooq.Identity<mineplex.database.tables.records.ClanServerRecord, java.lang.Integer> IDENTITY_clanServer = Identities0.IDENTITY_clanServer;
	public static final org.jooq.Identity<mineplex.database.tables.records.ClanShopItemRecord, java.lang.Integer> IDENTITY_clanShopItem = Identities0.IDENTITY_clanShopItem;
	public static final org.jooq.Identity<mineplex.database.tables.records.ClanTerritoryRecord, java.lang.Integer> IDENTITY_clanTerritory = Identities0.IDENTITY_clanTerritory;
	public static final org.jooq.Identity<mineplex.database.tables.records.EloRatingRecord, org.jooq.types.UInteger> IDENTITY_eloRating = Identities0.IDENTITY_eloRating;
	public static final org.jooq.Identity<mineplex.database.tables.records.FieldBlockRecord, java.lang.Integer> IDENTITY_fieldBlock = Identities0.IDENTITY_fieldBlock;
	public static final org.jooq.Identity<mineplex.database.tables.records.FieldMonsterRecord, java.lang.Integer> IDENTITY_fieldMonster = Identities0.IDENTITY_fieldMonster;
	public static final org.jooq.Identity<mineplex.database.tables.records.FieldOreRecord, java.lang.Integer> IDENTITY_fieldOre = Identities0.IDENTITY_fieldOre;
	public static final org.jooq.Identity<mineplex.database.tables.records.ItemCategoriesRecord, java.lang.Integer> IDENTITY_itemCategories = Identities0.IDENTITY_itemCategories;
	public static final org.jooq.Identity<mineplex.database.tables.records.ItemsRecord, java.lang.Integer> IDENTITY_items = Identities0.IDENTITY_items;
	public static final org.jooq.Identity<mineplex.database.tables.records.MailRecord, java.lang.Integer> IDENTITY_mail = Identities0.IDENTITY_mail;
	public static final org.jooq.Identity<mineplex.database.tables.records.MailboxRecord, java.lang.Integer> IDENTITY_mailbox = Identities0.IDENTITY_mailbox;
	public static final org.jooq.Identity<mineplex.database.tables.records.NpcsRecord, java.lang.Integer> IDENTITY_npcs = Identities0.IDENTITY_npcs;
	public static final org.jooq.Identity<mineplex.database.tables.records.PlayerMapRecord, java.lang.Integer> IDENTITY_playerMap = Identities0.IDENTITY_playerMap;
	public static final org.jooq.Identity<mineplex.database.tables.records.PollsRecord, java.lang.Integer> IDENTITY_polls = Identities0.IDENTITY_polls;
	public static final org.jooq.Identity<mineplex.database.tables.records.RankBenefitsRecord, java.lang.Integer> IDENTITY_rankBenefits = Identities0.IDENTITY_rankBenefits;
	public static final org.jooq.Identity<mineplex.database.tables.records.ServerPasswordRecord, java.lang.Integer> IDENTITY_serverPassword = Identities0.IDENTITY_serverPassword;
	public static final org.jooq.Identity<mineplex.database.tables.records.SpawnsRecord, java.lang.Integer> IDENTITY_spawns = Identities0.IDENTITY_spawns;
	public static final org.jooq.Identity<mineplex.database.tables.records.StatEventsRecord, org.jooq.types.UInteger> IDENTITY_statEvents = Identities0.IDENTITY_statEvents;
	public static final org.jooq.Identity<mineplex.database.tables.records.StatsRecord, java.lang.Integer> IDENTITY_stats = Identities0.IDENTITY_stats;
	public static final org.jooq.Identity<mineplex.database.tables.records.TasksRecord, java.lang.Integer> IDENTITY_tasks = Identities0.IDENTITY_tasks;
	public static final org.jooq.Identity<mineplex.database.tables.records.TransactionsRecord, java.lang.Integer> IDENTITY_transactions = Identities0.IDENTITY_transactions;

	// -------------------------------------------------------------------------
	// UNIQUE and PRIMARY KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountClanRecord> KEY_accountClan_PRIMARY = UniqueKeys0.KEY_accountClan_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountCoinTransactionsRecord> KEY_accountCoinTransactions_PRIMARY = UniqueKeys0.KEY_accountCoinTransactions_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountFriendRecord> KEY_accountFriend_PRIMARY = UniqueKeys0.KEY_accountFriend_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountFriendRecord> KEY_accountFriend_uuidIndex = UniqueKeys0.KEY_accountFriend_uuidIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountGemTransactionsRecord> KEY_accountGemTransactions_PRIMARY = UniqueKeys0.KEY_accountGemTransactions_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountIgnoreRecord> KEY_accountIgnore_PRIMARY = UniqueKeys0.KEY_accountIgnore_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountInventoryRecord> KEY_accountInventory_PRIMARY = UniqueKeys0.KEY_accountInventory_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountInventoryRecord> KEY_accountInventory_accountItemIndex = UniqueKeys0.KEY_accountInventory_accountItemIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord> KEY_accountPolls_PRIMARY = UniqueKeys0.KEY_accountPolls_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord> KEY_accountPolls_accountPollIndex = UniqueKeys0.KEY_accountPolls_accountPollIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPreferencesRecord> KEY_accountPreferences_PRIMARY = UniqueKeys0.KEY_accountPreferences_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPreferencesRecord> KEY_accountPreferences_uuid_index = UniqueKeys0.KEY_accountPreferences_uuid_index;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountsRecord> KEY_accounts_PRIMARY = UniqueKeys0.KEY_accounts_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountsRecord> KEY_accounts_uuidIndex = UniqueKeys0.KEY_accounts_uuidIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountStatRecord> KEY_accountStat_PRIMARY = UniqueKeys0.KEY_accountStat_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountStatsRecord> KEY_accountStats_PRIMARY = UniqueKeys0.KEY_accountStats_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountTasksRecord> KEY_accountTasks_PRIMARY = UniqueKeys0.KEY_accountTasks_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountTransactionsRecord> KEY_accountTransactions_PRIMARY = UniqueKeys0.KEY_accountTransactions_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ActiveTournamentsRecord> KEY_activeTournaments_PRIMARY = UniqueKeys0.KEY_activeTournaments_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.BonusRecord> KEY_bonus_PRIMARY = UniqueKeys0.KEY_bonus_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanAlliancesRecord> KEY_clanAlliances_PRIMARY = UniqueKeys0.KEY_clanAlliances_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanEnemiesRecord> KEY_clanEnemies_PRIMARY = UniqueKeys0.KEY_clanEnemies_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanEnemiesRecord> KEY_clanEnemies_unique_clanId = UniqueKeys0.KEY_clanEnemies_unique_clanId;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanEnemiesRecord> KEY_clanEnemies_unique_otherClanId = UniqueKeys0.KEY_clanEnemies_unique_otherClanId;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClansRecord> KEY_clans_PRIMARY = UniqueKeys0.KEY_clans_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClansRecord> KEY_clans_clanName = UniqueKeys0.KEY_clans_clanName;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanServerRecord> KEY_clanServer_PRIMARY = UniqueKeys0.KEY_clanServer_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanShopItemRecord> KEY_clanShopItem_PRIMARY = UniqueKeys0.KEY_clanShopItem_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanShopItemRecord> KEY_clanShopItem_shop_page_slot_UNIQUE = UniqueKeys0.KEY_clanShopItem_shop_page_slot_UNIQUE;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanTerritoryRecord> KEY_clanTerritory_PRIMARY = UniqueKeys0.KEY_clanTerritory_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanTerritoryRecord> KEY_clanTerritory_territory_server_chunk_UNIQUE = UniqueKeys0.KEY_clanTerritory_territory_server_chunk_UNIQUE;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.EloRatingRecord> KEY_eloRating_PRIMARY = UniqueKeys0.KEY_eloRating_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.EloRatingRecord> KEY_eloRating_uuid_gameType_index = UniqueKeys0.KEY_eloRating_uuid_gameType_index;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.FieldBlockRecord> KEY_fieldBlock_PRIMARY = UniqueKeys0.KEY_fieldBlock_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.FieldMonsterRecord> KEY_fieldMonster_PRIMARY = UniqueKeys0.KEY_fieldMonster_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.FieldOreRecord> KEY_fieldOre_PRIMARY = UniqueKeys0.KEY_fieldOre_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemCategoriesRecord> KEY_itemCategories_PRIMARY = UniqueKeys0.KEY_itemCategories_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemCategoriesRecord> KEY_itemCategories_nameIndex = UniqueKeys0.KEY_itemCategories_nameIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord> KEY_items_PRIMARY = UniqueKeys0.KEY_items_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord> KEY_items_uniqueNameCategoryIndex = UniqueKeys0.KEY_items_uniqueNameCategoryIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.MailRecord> KEY_mail_PRIMARY = UniqueKeys0.KEY_mail_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.MailboxRecord> KEY_mailbox_PRIMARY = UniqueKeys0.KEY_mailbox_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.NpcsRecord> KEY_npcs_PRIMARY = UniqueKeys0.KEY_npcs_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.PlayerMapRecord> KEY_playerMap_PRIMARY = UniqueKeys0.KEY_playerMap_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.PlayerMapRecord> KEY_playerMap_playerIndex = UniqueKeys0.KEY_playerMap_playerIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.PollsRecord> KEY_polls_PRIMARY = UniqueKeys0.KEY_polls_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.RankBenefitsRecord> KEY_rankBenefits_PRIMARY = UniqueKeys0.KEY_rankBenefits_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.ServerPasswordRecord> KEY_serverPassword_PRIMARY = UniqueKeys0.KEY_serverPassword_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.SpawnsRecord> KEY_spawns_PRIMARY = UniqueKeys0.KEY_spawns_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatEventsRecord> KEY_statEvents_PRIMARY = UniqueKeys0.KEY_statEvents_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatEventsRecord> KEY_statEvents_UK_DailyEntry = UniqueKeys0.KEY_statEvents_UK_DailyEntry;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatsRecord> KEY_stats_PRIMARY = UniqueKeys0.KEY_stats_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatsRecord> KEY_stats_nameIndex = UniqueKeys0.KEY_stats_nameIndex;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatTypesRecord> KEY_statTypes_PRIMARY = UniqueKeys0.KEY_statTypes_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatTypesRecord> KEY_statTypes_name = UniqueKeys0.KEY_statTypes_name;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.TasksRecord> KEY_tasks_PRIMARY = UniqueKeys0.KEY_tasks_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.TasksRecord> KEY_tasks_name_UNIQUE = UniqueKeys0.KEY_tasks_name_UNIQUE;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.TournamentLBRecord> KEY_TournamentLB_PRIMARY = UniqueKeys0.KEY_TournamentLB_PRIMARY;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.TournamentLBRecord> KEY_TournamentLB_UK_PlayerEntry = UniqueKeys0.KEY_TournamentLB_UK_PlayerEntry;
	public static final org.jooq.UniqueKey<mineplex.database.tables.records.TransactionsRecord> KEY_transactions_PRIMARY = UniqueKeys0.KEY_transactions_PRIMARY;

	// -------------------------------------------------------------------------
	// FOREIGN KEY definitions
	// -------------------------------------------------------------------------

	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountClanRecord, mineplex.database.tables.records.AccountsRecord> FK_accountClan_accounts = ForeignKeys0.FK_accountClan_accounts;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountClanRecord, mineplex.database.tables.records.ClansRecord> FK_accountClan_clans2 = ForeignKeys0.FK_accountClan_clans2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountCoinTransactionsRecord, mineplex.database.tables.records.AccountsRecord> FK_ACT_ACCOUNTS_ID = ForeignKeys0.FK_ACT_ACCOUNTS_ID;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountGemTransactionsRecord, mineplex.database.tables.records.AccountsRecord> accountGemTransactions_ibfk_1 = ForeignKeys0.accountGemTransactions_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountInventoryRecord, mineplex.database.tables.records.AccountsRecord> accountInventory_ibfk_1 = ForeignKeys0.accountInventory_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountInventoryRecord, mineplex.database.tables.records.ItemsRecord> accountInventory_ibfk_2 = ForeignKeys0.accountInventory_ibfk_2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountPollsRecord, mineplex.database.tables.records.AccountsRecord> accountPolls_ibfk_1 = ForeignKeys0.accountPolls_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountPollsRecord, mineplex.database.tables.records.PollsRecord> accountPolls_ibfk_2 = ForeignKeys0.accountPolls_ibfk_2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatRecord, mineplex.database.tables.records.AccountsRecord> accountStat_account = ForeignKeys0.accountStat_account;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatRecord, mineplex.database.tables.records.StatsRecord> accountStat_stat = ForeignKeys0.accountStat_stat;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatsRecord, mineplex.database.tables.records.AccountsRecord> accountStats_ibfk_1 = ForeignKeys0.accountStats_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatsRecord, mineplex.database.tables.records.StatsRecord> accountStats_ibfk_2 = ForeignKeys0.accountStats_ibfk_2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTasksRecord, mineplex.database.tables.records.AccountsRecord> ACCOUNTTASKS_ACCOUNTID = ForeignKeys0.ACCOUNTTASKS_ACCOUNTID;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTasksRecord, mineplex.database.tables.records.TasksRecord> ACCOUNTTASKS_TASKID = ForeignKeys0.ACCOUNTTASKS_TASKID;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTransactionsRecord, mineplex.database.tables.records.AccountsRecord> ACCOUNTTRANSACTIONS_ACCOUNTID = ForeignKeys0.ACCOUNTTRANSACTIONS_ACCOUNTID;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTransactionsRecord, mineplex.database.tables.records.TransactionsRecord> ACCOUNTTRANSACTIONS_TRANSACTIONID = ForeignKeys0.ACCOUNTTRANSACTIONS_TRANSACTIONID;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.BonusRecord, mineplex.database.tables.records.AccountsRecord> bonus_ibfk_1 = ForeignKeys0.bonus_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanAlliancesRecord, mineplex.database.tables.records.ClansRecord> clanAlliances_ibfk_2 = ForeignKeys0.clanAlliances_ibfk_2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanAlliancesRecord, mineplex.database.tables.records.ClansRecord> clanAlliances_ibfk_1 = ForeignKeys0.clanAlliances_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanEnemiesRecord, mineplex.database.tables.records.ClansRecord> clanEnemies_ibfk_1 = ForeignKeys0.clanEnemies_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanEnemiesRecord, mineplex.database.tables.records.ClansRecord> clanEnemies_ibfk_2 = ForeignKeys0.clanEnemies_ibfk_2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClansRecord, mineplex.database.tables.records.ClanServerRecord> clans_ibfk_1 = ForeignKeys0.clans_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanTerritoryRecord, mineplex.database.tables.records.ClansRecord> clanTerritory_ibfk_1 = ForeignKeys0.clanTerritory_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanTerritoryRecord, mineplex.database.tables.records.ClanServerRecord> clanTerritory_ibfk_2 = ForeignKeys0.clanTerritory_ibfk_2;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.ItemsRecord, mineplex.database.tables.records.ItemCategoriesRecord> items_ibfk_1 = ForeignKeys0.items_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.MailRecord, mineplex.database.tables.records.AccountsRecord> mail_ibfk_1 = ForeignKeys0.mail_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.MailboxRecord, mineplex.database.tables.records.AccountsRecord> mailbox_ibfk_1 = ForeignKeys0.mailbox_ibfk_1;
	public static final org.jooq.ForeignKey<mineplex.database.tables.records.RankBenefitsRecord, mineplex.database.tables.records.AccountsRecord> rankBenefits_ibfk_1 = ForeignKeys0.rankBenefits_ibfk_1;

	// -------------------------------------------------------------------------
	// [#1459] distribute members to avoid static initialisers > 64kb
	// -------------------------------------------------------------------------

	private static class Identities0 extends org.jooq.impl.AbstractKeys {
		public static org.jooq.Identity<mineplex.database.tables.records.AccountClanRecord, java.lang.Integer> IDENTITY_accountClan = createIdentity(mineplex.database.tables.AccountClan.accountClan, mineplex.database.tables.AccountClan.accountClan.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountCoinTransactionsRecord, java.lang.Integer> IDENTITY_accountCoinTransactions = createIdentity(mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions, mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountFriendRecord, java.lang.Integer> IDENTITY_accountFriend = createIdentity(mineplex.database.tables.AccountFriend.accountFriend, mineplex.database.tables.AccountFriend.accountFriend.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountGemTransactionsRecord, java.lang.Integer> IDENTITY_accountGemTransactions = createIdentity(mineplex.database.tables.AccountGemTransactions.accountGemTransactions, mineplex.database.tables.AccountGemTransactions.accountGemTransactions.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountIgnoreRecord, java.lang.Integer> IDENTITY_accountIgnore = createIdentity(mineplex.database.tables.AccountIgnore.accountIgnore, mineplex.database.tables.AccountIgnore.accountIgnore.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountInventoryRecord, java.lang.Integer> IDENTITY_accountInventory = createIdentity(mineplex.database.tables.AccountInventory.accountInventory, mineplex.database.tables.AccountInventory.accountInventory.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountPollsRecord, java.lang.Integer> IDENTITY_accountPolls = createIdentity(mineplex.database.tables.AccountPolls.accountPolls, mineplex.database.tables.AccountPolls.accountPolls.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountPreferencesRecord, java.lang.Integer> IDENTITY_accountPreferences = createIdentity(mineplex.database.tables.AccountPreferences.accountPreferences, mineplex.database.tables.AccountPreferences.accountPreferences.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountsRecord, java.lang.Integer> IDENTITY_accounts = createIdentity(mineplex.database.tables.Accounts.accounts, mineplex.database.tables.Accounts.accounts.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountStatsRecord, java.lang.Integer> IDENTITY_accountStats = createIdentity(mineplex.database.tables.AccountStats.accountStats, mineplex.database.tables.AccountStats.accountStats.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountTasksRecord, java.lang.Integer> IDENTITY_accountTasks = createIdentity(mineplex.database.tables.AccountTasks.accountTasks, mineplex.database.tables.AccountTasks.accountTasks.id);
		public static org.jooq.Identity<mineplex.database.tables.records.AccountTransactionsRecord, java.lang.Integer> IDENTITY_accountTransactions = createIdentity(mineplex.database.tables.AccountTransactions.accountTransactions, mineplex.database.tables.AccountTransactions.accountTransactions.id);
		public static org.jooq.Identity<mineplex.database.tables.records.BonusRecord, java.lang.Integer> IDENTITY_bonus = createIdentity(mineplex.database.tables.Bonus.bonus, mineplex.database.tables.Bonus.bonus.accountId);
		public static org.jooq.Identity<mineplex.database.tables.records.ClanAlliancesRecord, java.lang.Integer> IDENTITY_clanAlliances = createIdentity(mineplex.database.tables.ClanAlliances.clanAlliances, mineplex.database.tables.ClanAlliances.clanAlliances.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ClanEnemiesRecord, java.lang.Integer> IDENTITY_clanEnemies = createIdentity(mineplex.database.tables.ClanEnemies.clanEnemies, mineplex.database.tables.ClanEnemies.clanEnemies.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ClansRecord, java.lang.Integer> IDENTITY_clans = createIdentity(mineplex.database.tables.Clans.clans, mineplex.database.tables.Clans.clans.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ClanServerRecord, java.lang.Integer> IDENTITY_clanServer = createIdentity(mineplex.database.tables.ClanServer.clanServer, mineplex.database.tables.ClanServer.clanServer.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ClanShopItemRecord, java.lang.Integer> IDENTITY_clanShopItem = createIdentity(mineplex.database.tables.ClanShopItem.clanShopItem, mineplex.database.tables.ClanShopItem.clanShopItem.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ClanTerritoryRecord, java.lang.Integer> IDENTITY_clanTerritory = createIdentity(mineplex.database.tables.ClanTerritory.clanTerritory, mineplex.database.tables.ClanTerritory.clanTerritory.id);
		public static org.jooq.Identity<mineplex.database.tables.records.EloRatingRecord, org.jooq.types.UInteger> IDENTITY_eloRating = createIdentity(mineplex.database.tables.EloRating.eloRating, mineplex.database.tables.EloRating.eloRating.id);
		public static org.jooq.Identity<mineplex.database.tables.records.FieldBlockRecord, java.lang.Integer> IDENTITY_fieldBlock = createIdentity(mineplex.database.tables.FieldBlock.fieldBlock, mineplex.database.tables.FieldBlock.fieldBlock.id);
		public static org.jooq.Identity<mineplex.database.tables.records.FieldMonsterRecord, java.lang.Integer> IDENTITY_fieldMonster = createIdentity(mineplex.database.tables.FieldMonster.fieldMonster, mineplex.database.tables.FieldMonster.fieldMonster.id);
		public static org.jooq.Identity<mineplex.database.tables.records.FieldOreRecord, java.lang.Integer> IDENTITY_fieldOre = createIdentity(mineplex.database.tables.FieldOre.fieldOre, mineplex.database.tables.FieldOre.fieldOre.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ItemCategoriesRecord, java.lang.Integer> IDENTITY_itemCategories = createIdentity(mineplex.database.tables.ItemCategories.itemCategories, mineplex.database.tables.ItemCategories.itemCategories.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ItemsRecord, java.lang.Integer> IDENTITY_items = createIdentity(mineplex.database.tables.Items.items, mineplex.database.tables.Items.items.id);
		public static org.jooq.Identity<mineplex.database.tables.records.MailRecord, java.lang.Integer> IDENTITY_mail = createIdentity(mineplex.database.tables.Mail.mail, mineplex.database.tables.Mail.mail.id);
		public static org.jooq.Identity<mineplex.database.tables.records.MailboxRecord, java.lang.Integer> IDENTITY_mailbox = createIdentity(mineplex.database.tables.Mailbox.mailbox, mineplex.database.tables.Mailbox.mailbox.id);
		public static org.jooq.Identity<mineplex.database.tables.records.NpcsRecord, java.lang.Integer> IDENTITY_npcs = createIdentity(mineplex.database.tables.Npcs.npcs, mineplex.database.tables.Npcs.npcs.id);
		public static org.jooq.Identity<mineplex.database.tables.records.PlayerMapRecord, java.lang.Integer> IDENTITY_playerMap = createIdentity(mineplex.database.tables.PlayerMap.playerMap, mineplex.database.tables.PlayerMap.playerMap.id);
		public static org.jooq.Identity<mineplex.database.tables.records.PollsRecord, java.lang.Integer> IDENTITY_polls = createIdentity(mineplex.database.tables.Polls.polls, mineplex.database.tables.Polls.polls.id);
		public static org.jooq.Identity<mineplex.database.tables.records.RankBenefitsRecord, java.lang.Integer> IDENTITY_rankBenefits = createIdentity(mineplex.database.tables.RankBenefits.rankBenefits, mineplex.database.tables.RankBenefits.rankBenefits.id);
		public static org.jooq.Identity<mineplex.database.tables.records.ServerPasswordRecord, java.lang.Integer> IDENTITY_serverPassword = createIdentity(mineplex.database.tables.ServerPassword.serverPassword, mineplex.database.tables.ServerPassword.serverPassword.id);
		public static org.jooq.Identity<mineplex.database.tables.records.SpawnsRecord, java.lang.Integer> IDENTITY_spawns = createIdentity(mineplex.database.tables.Spawns.spawns, mineplex.database.tables.Spawns.spawns.id);
		public static org.jooq.Identity<mineplex.database.tables.records.StatEventsRecord, org.jooq.types.UInteger> IDENTITY_statEvents = createIdentity(mineplex.database.tables.StatEvents.statEvents, mineplex.database.tables.StatEvents.statEvents.eventId);
		public static org.jooq.Identity<mineplex.database.tables.records.StatsRecord, java.lang.Integer> IDENTITY_stats = createIdentity(mineplex.database.tables.Stats.stats, mineplex.database.tables.Stats.stats.id);
		public static org.jooq.Identity<mineplex.database.tables.records.TasksRecord, java.lang.Integer> IDENTITY_tasks = createIdentity(mineplex.database.tables.Tasks.tasks, mineplex.database.tables.Tasks.tasks.id);
		public static org.jooq.Identity<mineplex.database.tables.records.TransactionsRecord, java.lang.Integer> IDENTITY_transactions = createIdentity(mineplex.database.tables.Transactions.transactions, mineplex.database.tables.Transactions.transactions.id);
	}

	private static class UniqueKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountClanRecord> KEY_accountClan_PRIMARY = createUniqueKey(mineplex.database.tables.AccountClan.accountClan, mineplex.database.tables.AccountClan.accountClan.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountCoinTransactionsRecord> KEY_accountCoinTransactions_PRIMARY = createUniqueKey(mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions, mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountFriendRecord> KEY_accountFriend_PRIMARY = createUniqueKey(mineplex.database.tables.AccountFriend.accountFriend, mineplex.database.tables.AccountFriend.accountFriend.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountFriendRecord> KEY_accountFriend_uuidIndex = createUniqueKey(mineplex.database.tables.AccountFriend.accountFriend, mineplex.database.tables.AccountFriend.accountFriend.uuidSource, mineplex.database.tables.AccountFriend.accountFriend.uuidTarget);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountGemTransactionsRecord> KEY_accountGemTransactions_PRIMARY = createUniqueKey(mineplex.database.tables.AccountGemTransactions.accountGemTransactions, mineplex.database.tables.AccountGemTransactions.accountGemTransactions.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountIgnoreRecord> KEY_accountIgnore_PRIMARY = createUniqueKey(mineplex.database.tables.AccountIgnore.accountIgnore, mineplex.database.tables.AccountIgnore.accountIgnore.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountInventoryRecord> KEY_accountInventory_PRIMARY = createUniqueKey(mineplex.database.tables.AccountInventory.accountInventory, mineplex.database.tables.AccountInventory.accountInventory.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountInventoryRecord> KEY_accountInventory_accountItemIndex = createUniqueKey(mineplex.database.tables.AccountInventory.accountInventory, mineplex.database.tables.AccountInventory.accountInventory.accountId, mineplex.database.tables.AccountInventory.accountInventory.itemId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord> KEY_accountPolls_PRIMARY = createUniqueKey(mineplex.database.tables.AccountPolls.accountPolls, mineplex.database.tables.AccountPolls.accountPolls.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPollsRecord> KEY_accountPolls_accountPollIndex = createUniqueKey(mineplex.database.tables.AccountPolls.accountPolls, mineplex.database.tables.AccountPolls.accountPolls.accountId, mineplex.database.tables.AccountPolls.accountPolls.pollId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPreferencesRecord> KEY_accountPreferences_PRIMARY = createUniqueKey(mineplex.database.tables.AccountPreferences.accountPreferences, mineplex.database.tables.AccountPreferences.accountPreferences.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountPreferencesRecord> KEY_accountPreferences_uuid_index = createUniqueKey(mineplex.database.tables.AccountPreferences.accountPreferences, mineplex.database.tables.AccountPreferences.accountPreferences.uuid);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountsRecord> KEY_accounts_PRIMARY = createUniqueKey(mineplex.database.tables.Accounts.accounts, mineplex.database.tables.Accounts.accounts.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountsRecord> KEY_accounts_uuidIndex = createUniqueKey(mineplex.database.tables.Accounts.accounts, mineplex.database.tables.Accounts.accounts.uuid);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountStatRecord> KEY_accountStat_PRIMARY = createUniqueKey(mineplex.database.tables.AccountStat.accountStat, mineplex.database.tables.AccountStat.accountStat.accountId, mineplex.database.tables.AccountStat.accountStat.statId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountStatsRecord> KEY_accountStats_PRIMARY = createUniqueKey(mineplex.database.tables.AccountStats.accountStats, mineplex.database.tables.AccountStats.accountStats.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountTasksRecord> KEY_accountTasks_PRIMARY = createUniqueKey(mineplex.database.tables.AccountTasks.accountTasks, mineplex.database.tables.AccountTasks.accountTasks.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.AccountTransactionsRecord> KEY_accountTransactions_PRIMARY = createUniqueKey(mineplex.database.tables.AccountTransactions.accountTransactions, mineplex.database.tables.AccountTransactions.accountTransactions.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ActiveTournamentsRecord> KEY_activeTournaments_PRIMARY = createUniqueKey(mineplex.database.tables.ActiveTournaments.activeTournaments, mineplex.database.tables.ActiveTournaments.activeTournaments.name);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.BonusRecord> KEY_bonus_PRIMARY = createUniqueKey(mineplex.database.tables.Bonus.bonus, mineplex.database.tables.Bonus.bonus.accountId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanAlliancesRecord> KEY_clanAlliances_PRIMARY = createUniqueKey(mineplex.database.tables.ClanAlliances.clanAlliances, mineplex.database.tables.ClanAlliances.clanAlliances.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanEnemiesRecord> KEY_clanEnemies_PRIMARY = createUniqueKey(mineplex.database.tables.ClanEnemies.clanEnemies, mineplex.database.tables.ClanEnemies.clanEnemies.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanEnemiesRecord> KEY_clanEnemies_unique_clanId = createUniqueKey(mineplex.database.tables.ClanEnemies.clanEnemies, mineplex.database.tables.ClanEnemies.clanEnemies.clanId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanEnemiesRecord> KEY_clanEnemies_unique_otherClanId = createUniqueKey(mineplex.database.tables.ClanEnemies.clanEnemies, mineplex.database.tables.ClanEnemies.clanEnemies.otherClanId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClansRecord> KEY_clans_PRIMARY = createUniqueKey(mineplex.database.tables.Clans.clans, mineplex.database.tables.Clans.clans.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClansRecord> KEY_clans_clanName = createUniqueKey(mineplex.database.tables.Clans.clans, mineplex.database.tables.Clans.clans.serverId, mineplex.database.tables.Clans.clans.name);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanServerRecord> KEY_clanServer_PRIMARY = createUniqueKey(mineplex.database.tables.ClanServer.clanServer, mineplex.database.tables.ClanServer.clanServer.id, mineplex.database.tables.ClanServer.clanServer.serverName);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanShopItemRecord> KEY_clanShopItem_PRIMARY = createUniqueKey(mineplex.database.tables.ClanShopItem.clanShopItem, mineplex.database.tables.ClanShopItem.clanShopItem.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanShopItemRecord> KEY_clanShopItem_shop_page_slot_UNIQUE = createUniqueKey(mineplex.database.tables.ClanShopItem.clanShopItem, mineplex.database.tables.ClanShopItem.clanShopItem.shopName, mineplex.database.tables.ClanShopItem.clanShopItem.shopPage, mineplex.database.tables.ClanShopItem.clanShopItem.slot);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanTerritoryRecord> KEY_clanTerritory_PRIMARY = createUniqueKey(mineplex.database.tables.ClanTerritory.clanTerritory, mineplex.database.tables.ClanTerritory.clanTerritory.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ClanTerritoryRecord> KEY_clanTerritory_territory_server_chunk_UNIQUE = createUniqueKey(mineplex.database.tables.ClanTerritory.clanTerritory, mineplex.database.tables.ClanTerritory.clanTerritory.serverId, mineplex.database.tables.ClanTerritory.clanTerritory.chunk);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.EloRatingRecord> KEY_eloRating_PRIMARY = createUniqueKey(mineplex.database.tables.EloRating.eloRating, mineplex.database.tables.EloRating.eloRating.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.EloRatingRecord> KEY_eloRating_uuid_gameType_index = createUniqueKey(mineplex.database.tables.EloRating.eloRating, mineplex.database.tables.EloRating.eloRating.uuid, mineplex.database.tables.EloRating.eloRating.gamemode);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.FieldBlockRecord> KEY_fieldBlock_PRIMARY = createUniqueKey(mineplex.database.tables.FieldBlock.fieldBlock, mineplex.database.tables.FieldBlock.fieldBlock.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.FieldMonsterRecord> KEY_fieldMonster_PRIMARY = createUniqueKey(mineplex.database.tables.FieldMonster.fieldMonster, mineplex.database.tables.FieldMonster.fieldMonster.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.FieldOreRecord> KEY_fieldOre_PRIMARY = createUniqueKey(mineplex.database.tables.FieldOre.fieldOre, mineplex.database.tables.FieldOre.fieldOre.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemCategoriesRecord> KEY_itemCategories_PRIMARY = createUniqueKey(mineplex.database.tables.ItemCategories.itemCategories, mineplex.database.tables.ItemCategories.itemCategories.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemCategoriesRecord> KEY_itemCategories_nameIndex = createUniqueKey(mineplex.database.tables.ItemCategories.itemCategories, mineplex.database.tables.ItemCategories.itemCategories.name);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord> KEY_items_PRIMARY = createUniqueKey(mineplex.database.tables.Items.items, mineplex.database.tables.Items.items.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ItemsRecord> KEY_items_uniqueNameCategoryIndex = createUniqueKey(mineplex.database.tables.Items.items, mineplex.database.tables.Items.items.name, mineplex.database.tables.Items.items.categoryId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.MailRecord> KEY_mail_PRIMARY = createUniqueKey(mineplex.database.tables.Mail.mail, mineplex.database.tables.Mail.mail.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.MailboxRecord> KEY_mailbox_PRIMARY = createUniqueKey(mineplex.database.tables.Mailbox.mailbox, mineplex.database.tables.Mailbox.mailbox.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.NpcsRecord> KEY_npcs_PRIMARY = createUniqueKey(mineplex.database.tables.Npcs.npcs, mineplex.database.tables.Npcs.npcs.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.PlayerMapRecord> KEY_playerMap_PRIMARY = createUniqueKey(mineplex.database.tables.PlayerMap.playerMap, mineplex.database.tables.PlayerMap.playerMap.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.PlayerMapRecord> KEY_playerMap_playerIndex = createUniqueKey(mineplex.database.tables.PlayerMap.playerMap, mineplex.database.tables.PlayerMap.playerMap.playerName);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.PollsRecord> KEY_polls_PRIMARY = createUniqueKey(mineplex.database.tables.Polls.polls, mineplex.database.tables.Polls.polls.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.RankBenefitsRecord> KEY_rankBenefits_PRIMARY = createUniqueKey(mineplex.database.tables.RankBenefits.rankBenefits, mineplex.database.tables.RankBenefits.rankBenefits.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.ServerPasswordRecord> KEY_serverPassword_PRIMARY = createUniqueKey(mineplex.database.tables.ServerPassword.serverPassword, mineplex.database.tables.ServerPassword.serverPassword.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.SpawnsRecord> KEY_spawns_PRIMARY = createUniqueKey(mineplex.database.tables.Spawns.spawns, mineplex.database.tables.Spawns.spawns.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatEventsRecord> KEY_statEvents_PRIMARY = createUniqueKey(mineplex.database.tables.StatEvents.statEvents, mineplex.database.tables.StatEvents.statEvents.eventId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatEventsRecord> KEY_statEvents_UK_DailyEntry = createUniqueKey(mineplex.database.tables.StatEvents.statEvents, mineplex.database.tables.StatEvents.statEvents.accountId, mineplex.database.tables.StatEvents.statEvents.date, mineplex.database.tables.StatEvents.statEvents.gamemode, mineplex.database.tables.StatEvents.statEvents.serverGroup, mineplex.database.tables.StatEvents.statEvents.type);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatsRecord> KEY_stats_PRIMARY = createUniqueKey(mineplex.database.tables.Stats.stats, mineplex.database.tables.Stats.stats.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatsRecord> KEY_stats_nameIndex = createUniqueKey(mineplex.database.tables.Stats.stats, mineplex.database.tables.Stats.stats.name);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatTypesRecord> KEY_statTypes_PRIMARY = createUniqueKey(mineplex.database.tables.StatTypes.statTypes, mineplex.database.tables.StatTypes.statTypes.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.StatTypesRecord> KEY_statTypes_name = createUniqueKey(mineplex.database.tables.StatTypes.statTypes, mineplex.database.tables.StatTypes.statTypes.name);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.TasksRecord> KEY_tasks_PRIMARY = createUniqueKey(mineplex.database.tables.Tasks.tasks, mineplex.database.tables.Tasks.tasks.id);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.TasksRecord> KEY_tasks_name_UNIQUE = createUniqueKey(mineplex.database.tables.Tasks.tasks, mineplex.database.tables.Tasks.tasks.name);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.TournamentLBRecord> KEY_TournamentLB_PRIMARY = createUniqueKey(mineplex.database.tables.TournamentLB.TournamentLB, mineplex.database.tables.TournamentLB.TournamentLB.rank);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.TournamentLBRecord> KEY_TournamentLB_UK_PlayerEntry = createUniqueKey(mineplex.database.tables.TournamentLB.TournamentLB, mineplex.database.tables.TournamentLB.TournamentLB.accountId);
		public static final org.jooq.UniqueKey<mineplex.database.tables.records.TransactionsRecord> KEY_transactions_PRIMARY = createUniqueKey(mineplex.database.tables.Transactions.transactions, mineplex.database.tables.Transactions.transactions.id);
	}

	private static class ForeignKeys0 extends org.jooq.impl.AbstractKeys {
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountClanRecord, mineplex.database.tables.records.AccountsRecord> FK_accountClan_accounts = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountClan.accountClan, mineplex.database.tables.AccountClan.accountClan.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountClanRecord, mineplex.database.tables.records.ClansRecord> FK_accountClan_clans2 = createForeignKey(mineplex.database.Keys.KEY_clans_PRIMARY, mineplex.database.tables.AccountClan.accountClan, mineplex.database.tables.AccountClan.accountClan.clanId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountCoinTransactionsRecord, mineplex.database.tables.records.AccountsRecord> FK_ACT_ACCOUNTS_ID = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions, mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountGemTransactionsRecord, mineplex.database.tables.records.AccountsRecord> accountGemTransactions_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_uuidIndex, mineplex.database.tables.AccountGemTransactions.accountGemTransactions, mineplex.database.tables.AccountGemTransactions.accountGemTransactions.accounts_uuid);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountInventoryRecord, mineplex.database.tables.records.AccountsRecord> accountInventory_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountInventory.accountInventory, mineplex.database.tables.AccountInventory.accountInventory.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountInventoryRecord, mineplex.database.tables.records.ItemsRecord> accountInventory_ibfk_2 = createForeignKey(mineplex.database.Keys.KEY_items_PRIMARY, mineplex.database.tables.AccountInventory.accountInventory, mineplex.database.tables.AccountInventory.accountInventory.itemId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountPollsRecord, mineplex.database.tables.records.AccountsRecord> accountPolls_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountPolls.accountPolls, mineplex.database.tables.AccountPolls.accountPolls.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountPollsRecord, mineplex.database.tables.records.PollsRecord> accountPolls_ibfk_2 = createForeignKey(mineplex.database.Keys.KEY_polls_PRIMARY, mineplex.database.tables.AccountPolls.accountPolls, mineplex.database.tables.AccountPolls.accountPolls.pollId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatRecord, mineplex.database.tables.records.AccountsRecord> accountStat_account = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountStat.accountStat, mineplex.database.tables.AccountStat.accountStat.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatRecord, mineplex.database.tables.records.StatsRecord> accountStat_stat = createForeignKey(mineplex.database.Keys.KEY_stats_PRIMARY, mineplex.database.tables.AccountStat.accountStat, mineplex.database.tables.AccountStat.accountStat.statId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatsRecord, mineplex.database.tables.records.AccountsRecord> accountStats_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountStats.accountStats, mineplex.database.tables.AccountStats.accountStats.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountStatsRecord, mineplex.database.tables.records.StatsRecord> accountStats_ibfk_2 = createForeignKey(mineplex.database.Keys.KEY_stats_PRIMARY, mineplex.database.tables.AccountStats.accountStats, mineplex.database.tables.AccountStats.accountStats.statId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTasksRecord, mineplex.database.tables.records.AccountsRecord> ACCOUNTTASKS_ACCOUNTID = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountTasks.accountTasks, mineplex.database.tables.AccountTasks.accountTasks.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTasksRecord, mineplex.database.tables.records.TasksRecord> ACCOUNTTASKS_TASKID = createForeignKey(mineplex.database.Keys.KEY_tasks_PRIMARY, mineplex.database.tables.AccountTasks.accountTasks, mineplex.database.tables.AccountTasks.accountTasks.taskId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTransactionsRecord, mineplex.database.tables.records.AccountsRecord> ACCOUNTTRANSACTIONS_ACCOUNTID = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.AccountTransactions.accountTransactions, mineplex.database.tables.AccountTransactions.accountTransactions.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.AccountTransactionsRecord, mineplex.database.tables.records.TransactionsRecord> ACCOUNTTRANSACTIONS_TRANSACTIONID = createForeignKey(mineplex.database.Keys.KEY_transactions_PRIMARY, mineplex.database.tables.AccountTransactions.accountTransactions, mineplex.database.tables.AccountTransactions.accountTransactions.transactionId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.BonusRecord, mineplex.database.tables.records.AccountsRecord> bonus_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.Bonus.bonus, mineplex.database.tables.Bonus.bonus.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanAlliancesRecord, mineplex.database.tables.records.ClansRecord> clanAlliances_ibfk_2 = createForeignKey(mineplex.database.Keys.KEY_clans_PRIMARY, mineplex.database.tables.ClanAlliances.clanAlliances, mineplex.database.tables.ClanAlliances.clanAlliances.clanId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanAlliancesRecord, mineplex.database.tables.records.ClansRecord> clanAlliances_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_clans_PRIMARY, mineplex.database.tables.ClanAlliances.clanAlliances, mineplex.database.tables.ClanAlliances.clanAlliances.otherClanId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanEnemiesRecord, mineplex.database.tables.records.ClansRecord> clanEnemies_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_clans_PRIMARY, mineplex.database.tables.ClanEnemies.clanEnemies, mineplex.database.tables.ClanEnemies.clanEnemies.clanId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanEnemiesRecord, mineplex.database.tables.records.ClansRecord> clanEnemies_ibfk_2 = createForeignKey(mineplex.database.Keys.KEY_clans_PRIMARY, mineplex.database.tables.ClanEnemies.clanEnemies, mineplex.database.tables.ClanEnemies.clanEnemies.otherClanId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClansRecord, mineplex.database.tables.records.ClanServerRecord> clans_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_clanServer_PRIMARY, mineplex.database.tables.Clans.clans, mineplex.database.tables.Clans.clans.serverId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanTerritoryRecord, mineplex.database.tables.records.ClansRecord> clanTerritory_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_clans_PRIMARY, mineplex.database.tables.ClanTerritory.clanTerritory, mineplex.database.tables.ClanTerritory.clanTerritory.clanId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ClanTerritoryRecord, mineplex.database.tables.records.ClanServerRecord> clanTerritory_ibfk_2 = createForeignKey(mineplex.database.Keys.KEY_clanServer_PRIMARY, mineplex.database.tables.ClanTerritory.clanTerritory, mineplex.database.tables.ClanTerritory.clanTerritory.serverId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.ItemsRecord, mineplex.database.tables.records.ItemCategoriesRecord> items_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_itemCategories_PRIMARY, mineplex.database.tables.Items.items, mineplex.database.tables.Items.items.categoryId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.MailRecord, mineplex.database.tables.records.AccountsRecord> mail_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.Mail.mail, mineplex.database.tables.Mail.mail.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.MailboxRecord, mineplex.database.tables.records.AccountsRecord> mailbox_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.Mailbox.mailbox, mineplex.database.tables.Mailbox.mailbox.accountId);
		public static final org.jooq.ForeignKey<mineplex.database.tables.records.RankBenefitsRecord, mineplex.database.tables.records.AccountsRecord> rankBenefits_ibfk_1 = createForeignKey(mineplex.database.Keys.KEY_accounts_PRIMARY, mineplex.database.tables.RankBenefits.rankBenefits, mineplex.database.tables.RankBenefits.rankBenefits.accountId);
	}
}
