/**
 * This class is generated by jOOQ
 */
package mineplex.database;

/**
 * Convenience access to all tables in Account
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Account.accountClan
	 */
	public static final mineplex.database.tables.AccountClan accountClan = mineplex.database.tables.AccountClan.accountClan;

	/**
	 * The table Account.accountCoinTransactions
	 */
	public static final mineplex.database.tables.AccountCoinTransactions accountCoinTransactions = mineplex.database.tables.AccountCoinTransactions.accountCoinTransactions;

	/**
	 * The table Account.accountFriend
	 */
	public static final mineplex.database.tables.AccountFriend accountFriend = mineplex.database.tables.AccountFriend.accountFriend;

	/**
	 * The table Account.accountGemTransactions
	 */
	public static final mineplex.database.tables.AccountGemTransactions accountGemTransactions = mineplex.database.tables.AccountGemTransactions.accountGemTransactions;

	/**
	 * The table Account.accountIgnore
	 */
	public static final mineplex.database.tables.AccountIgnore accountIgnore = mineplex.database.tables.AccountIgnore.accountIgnore;

	/**
	 * The table Account.accountInventory
	 */
	public static final mineplex.database.tables.AccountInventory accountInventory = mineplex.database.tables.AccountInventory.accountInventory;

	/**
	 * The table Account.accountPolls
	 */
	public static final mineplex.database.tables.AccountPolls accountPolls = mineplex.database.tables.AccountPolls.accountPolls;

	/**
	 * The table Account.accountPreferences
	 */
	public static final mineplex.database.tables.AccountPreferences accountPreferences = mineplex.database.tables.AccountPreferences.accountPreferences;

	/**
	 * The table Account.accounts
	 */
	public static final mineplex.database.tables.Accounts accounts = mineplex.database.tables.Accounts.accounts;

	/**
	 * The table Account.accountStat
	 */
	public static final mineplex.database.tables.AccountStat accountStat = mineplex.database.tables.AccountStat.accountStat;

	/**
	 * The table Account.accountStats
	 */
	public static final mineplex.database.tables.AccountStats accountStats = mineplex.database.tables.AccountStats.accountStats;

	/**
	 * The table Account.accountTasks
	 */
	public static final mineplex.database.tables.AccountTasks accountTasks = mineplex.database.tables.AccountTasks.accountTasks;

	/**
	 * The table Account.accountTransactions
	 */
	public static final mineplex.database.tables.AccountTransactions accountTransactions = mineplex.database.tables.AccountTransactions.accountTransactions;

	/**
	 * The table Account.activeTournaments
	 */
	public static final mineplex.database.tables.ActiveTournaments activeTournaments = mineplex.database.tables.ActiveTournaments.activeTournaments;

	/**
	 * The table Account.bonus
	 */
	public static final mineplex.database.tables.Bonus bonus = mineplex.database.tables.Bonus.bonus;

	/**
	 * The table Account.clanAlliances
	 */
	public static final mineplex.database.tables.ClanAlliances clanAlliances = mineplex.database.tables.ClanAlliances.clanAlliances;

	/**
	 * The table Account.clanEnemies
	 */
	public static final mineplex.database.tables.ClanEnemies clanEnemies = mineplex.database.tables.ClanEnemies.clanEnemies;

	/**
	 * VIEW
	 */
	public static final mineplex.database.tables.ClanMember clanMember = mineplex.database.tables.ClanMember.clanMember;

	/**
	 * The table Account.clans
	 */
	public static final mineplex.database.tables.Clans clans = mineplex.database.tables.Clans.clans;

	/**
	 * The table Account.clanServer
	 */
	public static final mineplex.database.tables.ClanServer clanServer = mineplex.database.tables.ClanServer.clanServer;

	/**
	 * The table Account.clanShopItem
	 */
	public static final mineplex.database.tables.ClanShopItem clanShopItem = mineplex.database.tables.ClanShopItem.clanShopItem;

	/**
	 * The table Account.clanTerritory
	 */
	public static final mineplex.database.tables.ClanTerritory clanTerritory = mineplex.database.tables.ClanTerritory.clanTerritory;

	/**
	 * The table Account.eloRating
	 */
	public static final mineplex.database.tables.EloRating eloRating = mineplex.database.tables.EloRating.eloRating;

	/**
	 * The table Account.fieldBlock
	 */
	public static final mineplex.database.tables.FieldBlock fieldBlock = mineplex.database.tables.FieldBlock.fieldBlock;

	/**
	 * The table Account.fieldMonster
	 */
	public static final mineplex.database.tables.FieldMonster fieldMonster = mineplex.database.tables.FieldMonster.fieldMonster;

	/**
	 * The table Account.fieldOre
	 */
	public static final mineplex.database.tables.FieldOre fieldOre = mineplex.database.tables.FieldOre.fieldOre;

	/**
	 * The table Account.itemCategories
	 */
	public static final mineplex.database.tables.ItemCategories itemCategories = mineplex.database.tables.ItemCategories.itemCategories;

	/**
	 * The table Account.items
	 */
	public static final mineplex.database.tables.Items items = mineplex.database.tables.Items.items;

	/**
	 * The table Account.mail
	 */
	public static final mineplex.database.tables.Mail mail = mineplex.database.tables.Mail.mail;

	/**
	 * The table Account.mailbox
	 */
	public static final mineplex.database.tables.Mailbox mailbox = mineplex.database.tables.Mailbox.mailbox;

	/**
	 * The table Account.npcs
	 */
	public static final mineplex.database.tables.Npcs npcs = mineplex.database.tables.Npcs.npcs;

	/**
	 * The table Account.playerMap
	 */
	public static final mineplex.database.tables.PlayerMap playerMap = mineplex.database.tables.PlayerMap.playerMap;

	/**
	 * The table Account.polls
	 */
	public static final mineplex.database.tables.Polls polls = mineplex.database.tables.Polls.polls;

	/**
	 * The table Account.rankBenefits
	 */
	public static final mineplex.database.tables.RankBenefits rankBenefits = mineplex.database.tables.RankBenefits.rankBenefits;

	/**
	 * The table Account.serverPassword
	 */
	public static final mineplex.database.tables.ServerPassword serverPassword = mineplex.database.tables.ServerPassword.serverPassword;

	/**
	 * The table Account.spawns
	 */
	public static final mineplex.database.tables.Spawns spawns = mineplex.database.tables.Spawns.spawns;

	/**
	 * The table Account.statEvents
	 */
	public static final mineplex.database.tables.StatEvents statEvents = mineplex.database.tables.StatEvents.statEvents;

	/**
	 * The table Account.stats
	 */
	public static final mineplex.database.tables.Stats stats = mineplex.database.tables.Stats.stats;

	/**
	 * Stores a reference of the various types of statistics and their associated stat type IDs.
	 */
	public static final mineplex.database.tables.StatTypes statTypes = mineplex.database.tables.StatTypes.statTypes;

	/**
	 * The table Account.tasks
	 */
	public static final mineplex.database.tables.Tasks tasks = mineplex.database.tables.Tasks.tasks;

	/**
	 * The table Account.TournamentLB
	 */
	public static final mineplex.database.tables.TournamentLB TournamentLB = mineplex.database.tables.TournamentLB.TournamentLB;

	/**
	 * The table Account.transactions
	 */
	public static final mineplex.database.tables.Transactions transactions = mineplex.database.tables.Transactions.transactions;
}
