/**
 * This class is generated by jOOQ
 */
package ehnetwork.database;

import ehnetwork.database.tables.*;

/**
 * Convenience access to all tables in Account
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Tables {

	/**
	 * The table Account.accountClan
	 */
	public static final AccountClan accountClan = AccountClan.accountClan;

	/**
	 * The table Account.accountCoinTransactions
	 */
	public static final AccountCoinTransactions accountCoinTransactions = AccountCoinTransactions.accountCoinTransactions;

	/**
	 * The table Account.accountFriend
	 */
	public static final AccountFriend accountFriend = AccountFriend.accountFriend;

	/**
	 * The table Account.accountGemTransactions
	 */
	public static final AccountGemTransactions accountGemTransactions = AccountGemTransactions.accountGemTransactions;

	/**
	 * The table Account.accountIgnore
	 */
	public static final AccountIgnore accountIgnore = AccountIgnore.accountIgnore;

	/**
	 * The table Account.accountInventory
	 */
	public static final AccountInventory accountInventory = AccountInventory.accountInventory;

	/**
	 * The table Account.accountPolls
	 */
	public static final AccountPolls accountPolls = AccountPolls.accountPolls;

	/**
	 * The table Account.accountPreferences
	 */
	public static final AccountPreferences accountPreferences = AccountPreferences.accountPreferences;

	/**
	 * The table Account.accounts
	 */
	public static final Accounts accounts = Accounts.accounts;

	/**
	 * The table Account.accountStat
	 */
	public static final AccountStat accountStat = AccountStat.accountStat;

	/**
	 * The table Account.accountStats
	 */
	public static final AccountStats accountStats = AccountStats.accountStats;

	/**
	 * The table Account.accountTasks
	 */
	public static final AccountTasks accountTasks = AccountTasks.accountTasks;

	/**
	 * The table Account.accountTransactions
	 */
	public static final AccountTransactions accountTransactions = AccountTransactions.accountTransactions;

	/**
	 * The table Account.activeTournaments
	 */
	public static final ActiveTournaments activeTournaments = ActiveTournaments.activeTournaments;

	/**
	 * The table Account.bonus
	 */
	public static final Bonus bonus = Bonus.bonus;

	/**
	 * The table Account.clanAlliances
	 */
	public static final ClanAlliances clanAlliances = ClanAlliances.clanAlliances;

	/**
	 * The table Account.clanEnemies
	 */
	public static final ClanEnemies clanEnemies = ClanEnemies.clanEnemies;

	/**
	 * VIEW
	 */
	public static final ClanMember clanMember = ClanMember.clanMember;

	/**
	 * The table Account.clans
	 */
	public static final Clans clans = Clans.clans;

	/**
	 * The table Account.clanServer
	 */
	public static final ClanServer clanServer = ClanServer.clanServer;

	/**
	 * The table Account.clanShopItem
	 */
	public static final ClanShopItem clanShopItem = ClanShopItem.clanShopItem;

	/**
	 * The table Account.clanTerritory
	 */
	public static final ClanTerritory clanTerritory = ClanTerritory.clanTerritory;

	/**
	 * The table Account.eloRating
	 */
	public static final EloRating eloRating = EloRating.eloRating;

	/**
	 * The table Account.fieldBlock
	 */
	public static final FieldBlock fieldBlock = FieldBlock.fieldBlock;

	/**
	 * The table Account.fieldMonster
	 */
	public static final FieldMonster fieldMonster = FieldMonster.fieldMonster;

	/**
	 * The table Account.fieldOre
	 */
	public static final FieldOre fieldOre = FieldOre.fieldOre;

	/**
	 * The table Account.itemCategories
	 */
	public static final ItemCategories itemCategories = ItemCategories.itemCategories;

	/**
	 * The table Account.items
	 */
	public static final Items items = Items.items;

	/**
	 * The table Account.mail
	 */
	public static final Mail mail = Mail.mail;

	/**
	 * The table Account.mailbox
	 */
	public static final Mailbox mailbox = Mailbox.mailbox;

	/**
	 * The table Account.npcs
	 */
	public static final Npcs npcs = Npcs.npcs;

	/**
	 * The table Account.playerMap
	 */
	public static final PlayerMap playerMap = PlayerMap.playerMap;

	/**
	 * The table Account.polls
	 */
	public static final Polls polls = Polls.polls;

	/**
	 * The table Account.rankBenefits
	 */
	public static final RankBenefits rankBenefits = RankBenefits.rankBenefits;

	/**
	 * The table Account.serverPassword
	 */
	public static final ServerPassword serverPassword = ServerPassword.serverPassword;

	/**
	 * The table Account.spawns
	 */
	public static final Spawns spawns = Spawns.spawns;

	/**
	 * The table Account.statEvents
	 */
	public static final StatEvents statEvents = StatEvents.statEvents;

	/**
	 * The table Account.stats
	 */
	public static final Stats stats = Stats.stats;

	/**
	 * Stores a reference of the various types of statistics and their associated stat type IDs.
	 */
	public static final StatTypes statTypes = StatTypes.statTypes;

	/**
	 * The table Account.tasks
	 */
	public static final Tasks tasks = Tasks.tasks;

	/**
	 * The table Account.TournamentLB
	 */
	public static final ehnetwork.database.tables.TournamentLB TournamentLB = ehnetwork.database.tables.TournamentLB.TournamentLB;

	/**
	 * The table Account.transactions
	 */
	public static final Transactions transactions = Transactions.transactions;
}
