/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountGemTransactionsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountGemTransactions extends org.jooq.impl.TableImpl<AccountGemTransactionsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1280518241;

	/**
	 * The reference instance of <code>Account.accountGemTransactions</code>
	 */
	public static final AccountGemTransactions accountGemTransactions = new AccountGemTransactions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountGemTransactionsRecord> getRecordType() {
		return AccountGemTransactionsRecord.class;
	}

	/**
	 * The column <code>Account.accountGemTransactions.id</code>.
	 */
	public final org.jooq.TableField<AccountGemTransactionsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountGemTransactions.accounts_uuid</code>.
	 */
	public final org.jooq.TableField<AccountGemTransactionsRecord, java.lang.String> accounts_uuid = createField("accounts_uuid", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.accountGemTransactions.reason</code>.
	 */
	public final org.jooq.TableField<AccountGemTransactionsRecord, java.lang.String> reason = createField("reason", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.accountGemTransactions.gems</code>.
	 */
	public final org.jooq.TableField<AccountGemTransactionsRecord, java.lang.Integer> gems = createField("gems", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>Account.accountGemTransactions</code> table reference
	 */
	public AccountGemTransactions() {
		this("accountGemTransactions", null);
	}

	/**
	 * Create an aliased <code>Account.accountGemTransactions</code> table reference
	 */
	public AccountGemTransactions(java.lang.String alias) {
		this(alias, AccountGemTransactions.accountGemTransactions);
	}

	private AccountGemTransactions(java.lang.String alias, org.jooq.Table<AccountGemTransactionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountGemTransactions(java.lang.String alias, org.jooq.Table<AccountGemTransactionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountGemTransactionsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountGemTransactions;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountGemTransactionsRecord> getPrimaryKey() {
		return Keys.KEY_accountGemTransactions_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountGemTransactionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountGemTransactionsRecord>>asList(Keys.KEY_accountGemTransactions_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountGemTransactionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountGemTransactionsRecord, ?>>asList(Keys.accountGemTransactions_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountGemTransactions as(java.lang.String alias) {
		return new AccountGemTransactions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountGemTransactions rename(java.lang.String name) {
		return new AccountGemTransactions(name, null);
	}
}
