/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountStatsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountStats extends org.jooq.impl.TableImpl<AccountStatsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 794320538;

	/**
	 * The reference instance of <code>Account.accountStats</code>
	 */
	public static final AccountStats accountStats = new AccountStats();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountStatsRecord> getRecordType() {
		return AccountStatsRecord.class;
	}

	/**
	 * The column <code>Account.accountStats.id</code>.
	 */
	public final org.jooq.TableField<AccountStatsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStats.accountId</code>.
	 */
	public final org.jooq.TableField<AccountStatsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStats.statId</code>.
	 */
	public final org.jooq.TableField<AccountStatsRecord, java.lang.Integer> statId = createField("statId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStats.value</code>.
	 */
	public final org.jooq.TableField<AccountStatsRecord, java.lang.Integer> value = createField("value", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountStats</code> table reference
	 */
	public AccountStats() {
		this("accountStats", null);
	}

	/**
	 * Create an aliased <code>Account.accountStats</code> table reference
	 */
	public AccountStats(java.lang.String alias) {
		this(alias, AccountStats.accountStats);
	}

	private AccountStats(java.lang.String alias, org.jooq.Table<AccountStatsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountStats(java.lang.String alias, org.jooq.Table<AccountStatsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountStatsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountStats;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountStatsRecord> getPrimaryKey() {
		return Keys.KEY_accountStats_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountStatsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountStatsRecord>>asList(Keys.KEY_accountStats_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountStatsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountStatsRecord, ?>>asList(Keys.accountStats_ibfk_1, Keys.accountStats_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountStats as(java.lang.String alias) {
		return new AccountStats(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountStats rename(java.lang.String name) {
		return new AccountStats(name, null);
	}
}
