/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountClanRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountClan extends org.jooq.impl.TableImpl<AccountClanRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1838492867;

	/**
	 * The reference instance of <code>Account.accountClan</code>
	 */
	public static final AccountClan accountClan = new AccountClan();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountClanRecord> getRecordType() {
		return AccountClanRecord.class;
	}

	/**
	 * The column <code>Account.accountClan.id</code>.
	 */
	public final org.jooq.TableField<AccountClanRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.accountId</code>.
	 */
	public final org.jooq.TableField<AccountClanRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.clanId</code>.
	 */
	public final org.jooq.TableField<AccountClanRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountClan.clanRole</code>.
	 */
	public final org.jooq.TableField<AccountClanRecord, java.lang.String> clanRole = createField("clanRole", org.jooq.impl.SQLDataType.VARCHAR.length(50).nullable(false), this, "");

	/**
	 * Create a <code>Account.accountClan</code> table reference
	 */
	public AccountClan() {
		this("accountClan", null);
	}

	/**
	 * Create an aliased <code>Account.accountClan</code> table reference
	 */
	public AccountClan(java.lang.String alias) {
		this(alias, AccountClan.accountClan);
	}

	private AccountClan(java.lang.String alias, org.jooq.Table<AccountClanRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountClan(java.lang.String alias, org.jooq.Table<AccountClanRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountClanRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountClan;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountClanRecord> getPrimaryKey() {
		return Keys.KEY_accountClan_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountClanRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountClanRecord>>asList(Keys.KEY_accountClan_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountClanRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountClanRecord, ?>>asList(Keys.FK_accountClan_accounts, Keys.FK_accountClan_clans2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountClan as(java.lang.String alias) {
		return new AccountClan(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountClan rename(java.lang.String name) {
		return new AccountClan(name, null);
	}
}
