/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountIgnoreRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountIgnore extends org.jooq.impl.TableImpl<AccountIgnoreRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -191436863;

	/**
	 * The reference instance of <code>Account.accountIgnore</code>
	 */
	public static final AccountIgnore accountIgnore = new AccountIgnore();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountIgnoreRecord> getRecordType() {
		return AccountIgnoreRecord.class;
	}

	/**
	 * The column <code>Account.accountIgnore.id</code>.
	 */
	public final org.jooq.TableField<AccountIgnoreRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountIgnore.uuidIgnorer</code>.
	 */
	public final org.jooq.TableField<AccountIgnoreRecord, java.lang.String> uuidIgnorer = createField("uuidIgnorer", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * The column <code>Account.accountIgnore.uuidIgnored</code>.
	 */
	public final org.jooq.TableField<AccountIgnoreRecord, java.lang.String> uuidIgnored = createField("uuidIgnored", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>Account.accountIgnore</code> table reference
	 */
	public AccountIgnore() {
		this("accountIgnore", null);
	}

	/**
	 * Create an aliased <code>Account.accountIgnore</code> table reference
	 */
	public AccountIgnore(java.lang.String alias) {
		this(alias, AccountIgnore.accountIgnore);
	}

	private AccountIgnore(java.lang.String alias, org.jooq.Table<AccountIgnoreRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountIgnore(java.lang.String alias, org.jooq.Table<AccountIgnoreRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountIgnoreRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountIgnore;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountIgnoreRecord> getPrimaryKey() {
		return Keys.KEY_accountIgnore_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountIgnoreRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountIgnoreRecord>>asList(Keys.KEY_accountIgnore_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountIgnore as(java.lang.String alias) {
		return new AccountIgnore(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountIgnore rename(java.lang.String name) {
		return new AccountIgnore(name, null);
	}
}
