/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountPollsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountPolls extends org.jooq.impl.TableImpl<AccountPollsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1903716407;

	/**
	 * The reference instance of <code>Account.accountPolls</code>
	 */
	public static final AccountPolls accountPolls = new AccountPolls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountPollsRecord> getRecordType() {
		return AccountPollsRecord.class;
	}

	/**
	 * The column <code>Account.accountPolls.id</code>.
	 */
	public final org.jooq.TableField<AccountPollsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPolls.accountId</code>.
	 */
	public final org.jooq.TableField<AccountPollsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPolls.pollId</code>.
	 */
	public final org.jooq.TableField<AccountPollsRecord, java.lang.Integer> pollId = createField("pollId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountPolls.value</code>.
	 */
	public final org.jooq.TableField<AccountPollsRecord, java.lang.Byte> value = createField("value", org.jooq.impl.SQLDataType.TINYINT.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountPolls</code> table reference
	 */
	public AccountPolls() {
		this("accountPolls", null);
	}

	/**
	 * Create an aliased <code>Account.accountPolls</code> table reference
	 */
	public AccountPolls(java.lang.String alias) {
		this(alias, AccountPolls.accountPolls);
	}

	private AccountPolls(java.lang.String alias, org.jooq.Table<AccountPollsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountPolls(java.lang.String alias, org.jooq.Table<AccountPollsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountPollsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountPolls;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountPollsRecord> getPrimaryKey() {
		return Keys.KEY_accountPolls_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountPollsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountPollsRecord>>asList(Keys.KEY_accountPolls_PRIMARY, Keys.KEY_accountPolls_accountPollIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountPollsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountPollsRecord, ?>>asList(Keys.accountPolls_ibfk_1, Keys.accountPolls_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPolls as(java.lang.String alias) {
		return new AccountPolls(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountPolls rename(java.lang.String name) {
		return new AccountPolls(name, null);
	}
}
