/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountTasksRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTasks extends org.jooq.impl.TableImpl<AccountTasksRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1258627706;

	/**
	 * The reference instance of <code>Account.accountTasks</code>
	 */
	public static final AccountTasks accountTasks = new AccountTasks();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountTasksRecord> getRecordType() {
		return AccountTasksRecord.class;
	}

	/**
	 * The column <code>Account.accountTasks.id</code>.
	 */
	public final org.jooq.TableField<AccountTasksRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTasks.accountId</code>.
	 */
	public final org.jooq.TableField<AccountTasksRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTasks.taskId</code>.
	 */
	public final org.jooq.TableField<AccountTasksRecord, java.lang.Integer> taskId = createField("taskId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * Create a <code>Account.accountTasks</code> table reference
	 */
	public AccountTasks() {
		this("accountTasks", null);
	}

	/**
	 * Create an aliased <code>Account.accountTasks</code> table reference
	 */
	public AccountTasks(java.lang.String alias) {
		this(alias, AccountTasks.accountTasks);
	}

	private AccountTasks(java.lang.String alias, org.jooq.Table<AccountTasksRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountTasks(java.lang.String alias, org.jooq.Table<AccountTasksRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountTasksRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountTasks;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountTasksRecord> getPrimaryKey() {
		return Keys.KEY_accountTasks_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountTasksRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountTasksRecord>>asList(Keys.KEY_accountTasks_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountTasksRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountTasksRecord, ?>>asList(Keys.ACCOUNTTASKS_ACCOUNTID, Keys.ACCOUNTTASKS_TASKID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountTasks as(java.lang.String alias) {
		return new AccountTasks(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountTasks rename(java.lang.String name) {
		return new AccountTasks(name, null);
	}
}
