/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountTransactionsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountTransactions extends org.jooq.impl.TableImpl<AccountTransactionsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 628330770;

	/**
	 * The reference instance of <code>Account.accountTransactions</code>
	 */
	public static final AccountTransactions accountTransactions = new AccountTransactions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountTransactionsRecord> getRecordType() {
		return AccountTransactionsRecord.class;
	}

	/**
	 * The column <code>Account.accountTransactions.id</code>.
	 */
	public final org.jooq.TableField<AccountTransactionsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTransactions.accountId</code>.
	 */
	public final org.jooq.TableField<AccountTransactionsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTransactions.transactionId</code>.
	 */
	public final org.jooq.TableField<AccountTransactionsRecord, java.lang.Integer> transactionId = createField("transactionId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountTransactions.coins</code>.
	 */
	public final org.jooq.TableField<AccountTransactionsRecord, java.lang.Integer> coins = createField("coins", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>Account.accountTransactions.gems</code>.
	 */
	public final org.jooq.TableField<AccountTransactionsRecord, java.lang.Integer> gems = createField("gems", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountTransactions</code> table reference
	 */
	public AccountTransactions() {
		this("accountTransactions", null);
	}

	/**
	 * Create an aliased <code>Account.accountTransactions</code> table reference
	 */
	public AccountTransactions(java.lang.String alias) {
		this(alias, AccountTransactions.accountTransactions);
	}

	private AccountTransactions(java.lang.String alias, org.jooq.Table<AccountTransactionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountTransactions(java.lang.String alias, org.jooq.Table<AccountTransactionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<AccountTransactionsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_accountTransactions;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountTransactionsRecord> getPrimaryKey() {
		return Keys.KEY_accountTransactions_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountTransactionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountTransactionsRecord>>asList(Keys.KEY_accountTransactions_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountTransactionsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountTransactionsRecord, ?>>asList(Keys.ACCOUNTTRANSACTIONS_ACCOUNTID, Keys.ACCOUNTTRANSACTIONS_TRANSACTIONID);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountTransactions as(java.lang.String alias) {
		return new AccountTransactions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountTransactions rename(java.lang.String name) {
		return new AccountTransactions(name, null);
	}
}
