/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.AccountStatRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountStat extends org.jooq.impl.TableImpl<AccountStatRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 956897097;

	/**
	 * The reference instance of <code>Account.accountStat</code>
	 */
	public static final AccountStat accountStat = new AccountStat();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<AccountStatRecord> getRecordType() {
		return AccountStatRecord.class;
	}

	/**
	 * The column <code>Account.accountStat.accountId</code>.
	 */
	public final org.jooq.TableField<AccountStatRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStat.statId</code>.
	 */
	public final org.jooq.TableField<AccountStatRecord, java.lang.Integer> statId = createField("statId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.accountStat.value</code>.
	 */
	public final org.jooq.TableField<AccountStatRecord, java.lang.Long> value = createField("value", org.jooq.impl.SQLDataType.BIGINT.defaulted(true), this, "");

	/**
	 * Create a <code>Account.accountStat</code> table reference
	 */
	public AccountStat() {
		this("accountStat", null);
	}

	/**
	 * Create an aliased <code>Account.accountStat</code> table reference
	 */
	public AccountStat(java.lang.String alias) {
		this(alias, AccountStat.accountStat);
	}

	private AccountStat(java.lang.String alias, org.jooq.Table<AccountStatRecord> aliased) {
		this(alias, aliased, null);
	}

	private AccountStat(java.lang.String alias, org.jooq.Table<AccountStatRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<AccountStatRecord> getPrimaryKey() {
		return Keys.KEY_accountStat_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<AccountStatRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<AccountStatRecord>>asList(Keys.KEY_accountStat_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<AccountStatRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<AccountStatRecord, ?>>asList(Keys.accountStat_account, Keys.accountStat_stat);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountStat as(java.lang.String alias) {
		return new AccountStat(alias, this);
	}

	/**
	 * Rename this table
	 */
	public AccountStat rename(java.lang.String name) {
		return new AccountStat(name, null);
	}
}
