/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.ClanEnemiesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanEnemies extends org.jooq.impl.TableImpl<ClanEnemiesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 7530567;

	/**
	 * The reference instance of <code>Account.clanEnemies</code>
	 */
	public static final ClanEnemies clanEnemies = new ClanEnemies();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ClanEnemiesRecord> getRecordType() {
		return ClanEnemiesRecord.class;
	}

	/**
	 * The column <code>Account.clanEnemies.id</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanEnemies.clanId</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanEnemies.otherClanId</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> otherClanId = createField("otherClanId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanEnemies.initiator</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Boolean> initiator = createField("initiator", org.jooq.impl.SQLDataType.BIT.nullable(false), this, "");

	/**
	 * The column <code>Account.clanEnemies.timeFormed</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.sql.Timestamp> timeFormed = createField("timeFormed", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.clanEnemies.clanScore</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> clanScore = createField("clanScore", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>Account.clanEnemies.otherClanScore</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> otherClanScore = createField("otherClanScore", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * The column <code>Account.clanEnemies.clanKills</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> clanKills = createField("clanKills", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.clanEnemies.otherClanKills</code>.
	 */
	public final org.jooq.TableField<ClanEnemiesRecord, java.lang.Integer> otherClanKills = createField("otherClanKills", org.jooq.impl.SQLDataType.INTEGER.defaulted(true), this, "");

	/**
	 * Create a <code>Account.clanEnemies</code> table reference
	 */
	public ClanEnemies() {
		this("clanEnemies", null);
	}

	/**
	 * Create an aliased <code>Account.clanEnemies</code> table reference
	 */
	public ClanEnemies(java.lang.String alias) {
		this(alias, ClanEnemies.clanEnemies);
	}

	private ClanEnemies(java.lang.String alias, org.jooq.Table<ClanEnemiesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanEnemies(java.lang.String alias, org.jooq.Table<ClanEnemiesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ClanEnemiesRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_clanEnemies;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ClanEnemiesRecord> getPrimaryKey() {
		return Keys.KEY_clanEnemies_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ClanEnemiesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ClanEnemiesRecord>>asList(Keys.KEY_clanEnemies_PRIMARY, Keys.KEY_clanEnemies_unique_clanId, Keys.KEY_clanEnemies_unique_otherClanId);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ClanEnemiesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ClanEnemiesRecord, ?>>asList(Keys.clanEnemies_ibfk_1, Keys.clanEnemies_ibfk_2);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanEnemies as(java.lang.String alias) {
		return new ClanEnemies(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ClanEnemies rename(java.lang.String name) {
		return new ClanEnemies(name, null);
	}
}
