/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.ClanServerRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanServer extends org.jooq.impl.TableImpl<ClanServerRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -566894974;

	/**
	 * The reference instance of <code>Account.clanServer</code>
	 */
	public static final ClanServer clanServer = new ClanServer();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ClanServerRecord> getRecordType() {
		return ClanServerRecord.class;
	}

	/**
	 * The column <code>Account.clanServer.id</code>.
	 */
	public final org.jooq.TableField<ClanServerRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanServer.serverName</code>.
	 */
	public final org.jooq.TableField<ClanServerRecord, java.lang.String> serverName = createField("serverName", org.jooq.impl.SQLDataType.VARCHAR.length(100).nullable(false), this, "");

	/**
	 * Create a <code>Account.clanServer</code> table reference
	 */
	public ClanServer() {
		this("clanServer", null);
	}

	/**
	 * Create an aliased <code>Account.clanServer</code> table reference
	 */
	public ClanServer(java.lang.String alias) {
		this(alias, ClanServer.clanServer);
	}

	private ClanServer(java.lang.String alias, org.jooq.Table<ClanServerRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanServer(java.lang.String alias, org.jooq.Table<ClanServerRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ClanServerRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_clanServer;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ClanServerRecord> getPrimaryKey() {
		return Keys.KEY_clanServer_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ClanServerRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ClanServerRecord>>asList(Keys.KEY_clanServer_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanServer as(java.lang.String alias) {
		return new ClanServer(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ClanServer rename(java.lang.String name) {
		return new ClanServer(name, null);
	}
}
