/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.ClanAlliancesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanAlliances extends org.jooq.impl.TableImpl<ClanAlliancesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 2034100059;

	/**
	 * The reference instance of <code>Account.clanAlliances</code>
	 */
	public static final ClanAlliances clanAlliances = new ClanAlliances();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ClanAlliancesRecord> getRecordType() {
		return ClanAlliancesRecord.class;
	}

	/**
	 * The column <code>Account.clanAlliances.id</code>.
	 */
	public final org.jooq.TableField<ClanAlliancesRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.clanAlliances.clanId</code>.
	 */
	public final org.jooq.TableField<ClanAlliancesRecord, java.lang.Integer> clanId = createField("clanId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.clanAlliances.otherClanId</code>.
	 */
	public final org.jooq.TableField<ClanAlliancesRecord, java.lang.Integer> otherClanId = createField("otherClanId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.clanAlliances.trusted</code>.
	 */
	public final org.jooq.TableField<ClanAlliancesRecord, java.lang.Boolean> trusted = createField("trusted", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * Create a <code>Account.clanAlliances</code> table reference
	 */
	public ClanAlliances() {
		this("clanAlliances", null);
	}

	/**
	 * Create an aliased <code>Account.clanAlliances</code> table reference
	 */
	public ClanAlliances(java.lang.String alias) {
		this(alias, ClanAlliances.clanAlliances);
	}

	private ClanAlliances(java.lang.String alias, org.jooq.Table<ClanAlliancesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ClanAlliances(java.lang.String alias, org.jooq.Table<ClanAlliancesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ClanAlliancesRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_clanAlliances;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ClanAlliancesRecord> getPrimaryKey() {
		return Keys.KEY_clanAlliances_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ClanAlliancesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ClanAlliancesRecord>>asList(Keys.KEY_clanAlliances_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ClanAlliancesRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ClanAlliancesRecord, ?>>asList(Keys.clanAlliances_ibfk_2, Keys.clanAlliances_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanAlliances as(java.lang.String alias) {
		return new ClanAlliances(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ClanAlliances rename(java.lang.String name) {
		return new ClanAlliances(name, null);
	}
}
