/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.EloRatingRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EloRating extends org.jooq.impl.TableImpl<EloRatingRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -747680746;

	/**
	 * The reference instance of <code>Account.eloRating</code>
	 */
	public static final EloRating eloRating = new EloRating();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<EloRatingRecord> getRecordType() {
		return EloRatingRecord.class;
	}

	/**
	 * The column <code>Account.eloRating.id</code>.
	 */
	public final org.jooq.TableField<EloRatingRecord, org.jooq.types.UInteger> id = createField("id", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.uuid</code>.
	 */
	public final org.jooq.TableField<EloRatingRecord, java.lang.String> uuid = createField("uuid", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.gamemode</code>.
	 */
	public final org.jooq.TableField<EloRatingRecord, org.jooq.types.UByte> gamemode = createField("gamemode", org.jooq.impl.SQLDataType.TINYINTUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.matchesPlayed</code>.
	 */
	public final org.jooq.TableField<EloRatingRecord, org.jooq.types.UInteger> matchesPlayed = createField("matchesPlayed", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.eloRating.elo</code>.
	 */
	public final org.jooq.TableField<EloRatingRecord, java.lang.Integer> elo = createField("elo", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.eloRating.gameType</code>.
	 */
	public final org.jooq.TableField<EloRatingRecord, java.lang.String> gameType = createField("gameType", org.jooq.impl.SQLDataType.VARCHAR.length(40).nullable(false), this, "");

	/**
	 * Create a <code>Account.eloRating</code> table reference
	 */
	public EloRating() {
		this("eloRating", null);
	}

	/**
	 * Create an aliased <code>Account.eloRating</code> table reference
	 */
	public EloRating(java.lang.String alias) {
		this(alias, EloRating.eloRating);
	}

	private EloRating(java.lang.String alias, org.jooq.Table<EloRatingRecord> aliased) {
		this(alias, aliased, null);
	}

	private EloRating(java.lang.String alias, org.jooq.Table<EloRatingRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<EloRatingRecord, org.jooq.types.UInteger> getIdentity() {
		return Keys.IDENTITY_eloRating;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<EloRatingRecord> getPrimaryKey() {
		return Keys.KEY_eloRating_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<EloRatingRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<EloRatingRecord>>asList(Keys.KEY_eloRating_PRIMARY, Keys.KEY_eloRating_uuid_gameType_index);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRating as(java.lang.String alias) {
		return new EloRating(alias, this);
	}

	/**
	 * Rename this table
	 */
	public EloRating rename(java.lang.String name) {
		return new EloRating(name, null);
	}
}
