/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.ItemsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Items extends org.jooq.impl.TableImpl<ItemsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1044139841;

	/**
	 * The reference instance of <code>Account.items</code>
	 */
	public static final Items items = new Items();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ItemsRecord> getRecordType() {
		return ItemsRecord.class;
	}

	/**
	 * The column <code>Account.items.id</code>.
	 */
	public final org.jooq.TableField<ItemsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.items.name</code>.
	 */
	public final org.jooq.TableField<ItemsRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * The column <code>Account.items.categoryId</code>.
	 */
	public final org.jooq.TableField<ItemsRecord, java.lang.Integer> categoryId = createField("categoryId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.items.rarity</code>.
	 */
	public final org.jooq.TableField<ItemsRecord, java.lang.Integer> rarity = createField("rarity", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * Create a <code>Account.items</code> table reference
	 */
	public Items() {
		this("items", null);
	}

	/**
	 * Create an aliased <code>Account.items</code> table reference
	 */
	public Items(java.lang.String alias) {
		this(alias, Items.items);
	}

	private Items(java.lang.String alias, org.jooq.Table<ItemsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Items(java.lang.String alias, org.jooq.Table<ItemsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ItemsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_items;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ItemsRecord> getPrimaryKey() {
		return Keys.KEY_items_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ItemsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ItemsRecord>>asList(Keys.KEY_items_PRIMARY, Keys.KEY_items_uniqueNameCategoryIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<ItemsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<ItemsRecord, ?>>asList(Keys.items_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Items as(java.lang.String alias) {
		return new Items(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Items rename(java.lang.String name) {
		return new Items(name, null);
	}
}
