/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.ItemCategoriesRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ItemCategories extends org.jooq.impl.TableImpl<ItemCategoriesRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1747950682;

	/**
	 * The reference instance of <code>Account.itemCategories</code>
	 */
	public static final ItemCategories itemCategories = new ItemCategories();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<ItemCategoriesRecord> getRecordType() {
		return ItemCategoriesRecord.class;
	}

	/**
	 * The column <code>Account.itemCategories.id</code>.
	 */
	public final org.jooq.TableField<ItemCategoriesRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.itemCategories.name</code>.
	 */
	public final org.jooq.TableField<ItemCategoriesRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.itemCategories</code> table reference
	 */
	public ItemCategories() {
		this("itemCategories", null);
	}

	/**
	 * Create an aliased <code>Account.itemCategories</code> table reference
	 */
	public ItemCategories(java.lang.String alias) {
		this(alias, ItemCategories.itemCategories);
	}

	private ItemCategories(java.lang.String alias, org.jooq.Table<ItemCategoriesRecord> aliased) {
		this(alias, aliased, null);
	}

	private ItemCategories(java.lang.String alias, org.jooq.Table<ItemCategoriesRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<ItemCategoriesRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_itemCategories;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<ItemCategoriesRecord> getPrimaryKey() {
		return Keys.KEY_itemCategories_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<ItemCategoriesRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<ItemCategoriesRecord>>asList(Keys.KEY_itemCategories_PRIMARY, Keys.KEY_itemCategories_nameIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ItemCategories as(java.lang.String alias) {
		return new ItemCategories(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ItemCategories rename(java.lang.String name) {
		return new ItemCategories(name, null);
	}
}
