/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.MailRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Mail extends org.jooq.impl.TableImpl<MailRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 819731633;

	/**
	 * The reference instance of <code>Account.mail</code>
	 */
	public static final Mail mail = new Mail();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<MailRecord> getRecordType() {
		return MailRecord.class;
	}

	/**
	 * The column <code>Account.mail.id</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.mail.accountId</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.mail.sender</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.lang.String> sender = createField("sender", org.jooq.impl.SQLDataType.VARCHAR.length(64).nullable(false), this, "");

	/**
	 * The column <code>Account.mail.message</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.lang.String> message = createField("message", org.jooq.impl.SQLDataType.VARCHAR.length(1024).nullable(false), this, "");

	/**
	 * The column <code>Account.mail.archived</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.lang.Byte> archived = createField("archived", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.mail.deleted</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.lang.Byte> deleted = createField("deleted", org.jooq.impl.SQLDataType.TINYINT.nullable(false).defaulted(true), this, "");

	/**
	 * The column <code>Account.mail.timeSent</code>.
	 */
	public final org.jooq.TableField<MailRecord, java.sql.Timestamp> timeSent = createField("timeSent", org.jooq.impl.SQLDataType.TIMESTAMP.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.mail</code> table reference
	 */
	public Mail() {
		this("mail", null);
	}

	/**
	 * Create an aliased <code>Account.mail</code> table reference
	 */
	public Mail(java.lang.String alias) {
		this(alias, Mail.mail);
	}

	private Mail(java.lang.String alias, org.jooq.Table<MailRecord> aliased) {
		this(alias, aliased, null);
	}

	private Mail(java.lang.String alias, org.jooq.Table<MailRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<MailRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_mail;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<MailRecord> getPrimaryKey() {
		return Keys.KEY_mail_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<MailRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<MailRecord>>asList(Keys.KEY_mail_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<MailRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<MailRecord, ?>>asList(Keys.mail_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Mail as(java.lang.String alias) {
		return new Mail(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Mail rename(java.lang.String name) {
		return new Mail(name, null);
	}
}
