/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.PollsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Polls extends org.jooq.impl.TableImpl<PollsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 2116541612;

	/**
	 * The reference instance of <code>Account.polls</code>
	 */
	public static final Polls polls = new Polls();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<PollsRecord> getRecordType() {
		return PollsRecord.class;
	}

	/**
	 * The column <code>Account.polls.id</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.polls.enabled</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.Boolean> enabled = createField("enabled", org.jooq.impl.SQLDataType.BIT, this, "");

	/**
	 * The column <code>Account.polls.question</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.String> question = createField("question", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>Account.polls.answerA</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.String> answerA = createField("answerA", org.jooq.impl.SQLDataType.VARCHAR.length(256).nullable(false), this, "");

	/**
	 * The column <code>Account.polls.answerB</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.String> answerB = createField("answerB", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>Account.polls.answerC</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.String> answerC = createField("answerC", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>Account.polls.answerD</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.String> answerD = createField("answerD", org.jooq.impl.SQLDataType.VARCHAR.length(256), this, "");

	/**
	 * The column <code>Account.polls.coinReward</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.Integer> coinReward = createField("coinReward", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.polls.displayType</code>.
	 */
	public final org.jooq.TableField<PollsRecord, java.lang.Integer> displayType = createField("displayType", org.jooq.impl.SQLDataType.INTEGER.nullable(false).defaulted(true), this, "");

	/**
	 * Create a <code>Account.polls</code> table reference
	 */
	public Polls() {
		this("polls", null);
	}

	/**
	 * Create an aliased <code>Account.polls</code> table reference
	 */
	public Polls(java.lang.String alias) {
		this(alias, Polls.polls);
	}

	private Polls(java.lang.String alias, org.jooq.Table<PollsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Polls(java.lang.String alias, org.jooq.Table<PollsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<PollsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_polls;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<PollsRecord> getPrimaryKey() {
		return Keys.KEY_polls_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<PollsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<PollsRecord>>asList(Keys.KEY_polls_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Polls as(java.lang.String alias) {
		return new Polls(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Polls rename(java.lang.String name) {
		return new Polls(name, null);
	}
}
