/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.RankBenefitsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class RankBenefits extends org.jooq.impl.TableImpl<RankBenefitsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 1274456623;

	/**
	 * The reference instance of <code>Account.rankBenefits</code>
	 */
	public static final RankBenefits rankBenefits = new RankBenefits();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<RankBenefitsRecord> getRecordType() {
		return RankBenefitsRecord.class;
	}

	/**
	 * The column <code>Account.rankBenefits.id</code>.
	 */
	public final org.jooq.TableField<RankBenefitsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.rankBenefits.accountId</code>.
	 */
	public final org.jooq.TableField<RankBenefitsRecord, java.lang.Integer> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGER, this, "");

	/**
	 * The column <code>Account.rankBenefits.benefit</code>.
	 */
	public final org.jooq.TableField<RankBenefitsRecord, java.lang.String> benefit = createField("benefit", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.rankBenefits</code> table reference
	 */
	public RankBenefits() {
		this("rankBenefits", null);
	}

	/**
	 * Create an aliased <code>Account.rankBenefits</code> table reference
	 */
	public RankBenefits(java.lang.String alias) {
		this(alias, RankBenefits.rankBenefits);
	}

	private RankBenefits(java.lang.String alias, org.jooq.Table<RankBenefitsRecord> aliased) {
		this(alias, aliased, null);
	}

	private RankBenefits(java.lang.String alias, org.jooq.Table<RankBenefitsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<RankBenefitsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_rankBenefits;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<RankBenefitsRecord> getPrimaryKey() {
		return Keys.KEY_rankBenefits_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<RankBenefitsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<RankBenefitsRecord>>asList(Keys.KEY_rankBenefits_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.ForeignKey<RankBenefitsRecord, ?>> getReferences() {
		return java.util.Arrays.<org.jooq.ForeignKey<RankBenefitsRecord, ?>>asList(Keys.rankBenefits_ibfk_1);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public RankBenefits as(java.lang.String alias) {
		return new RankBenefits(alias, this);
	}

	/**
	 * Rename this table
	 */
	public RankBenefits rename(java.lang.String name) {
		return new RankBenefits(name, null);
	}
}
