/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.StatsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Stats extends org.jooq.impl.TableImpl<StatsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -1426984538;

	/**
	 * The reference instance of <code>Account.stats</code>
	 */
	public static final Stats stats = new Stats();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<StatsRecord> getRecordType() {
		return StatsRecord.class;
	}

	/**
	 * The column <code>Account.stats.id</code>.
	 */
	public final org.jooq.TableField<StatsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.stats.name</code>.
	 */
	public final org.jooq.TableField<StatsRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(100), this, "");

	/**
	 * Create a <code>Account.stats</code> table reference
	 */
	public Stats() {
		this("stats", null);
	}

	/**
	 * Create an aliased <code>Account.stats</code> table reference
	 */
	public Stats(java.lang.String alias) {
		this(alias, Stats.stats);
	}

	private Stats(java.lang.String alias, org.jooq.Table<StatsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Stats(java.lang.String alias, org.jooq.Table<StatsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<StatsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_stats;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<StatsRecord> getPrimaryKey() {
		return Keys.KEY_stats_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<StatsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<StatsRecord>>asList(Keys.KEY_stats_PRIMARY, Keys.KEY_stats_nameIndex);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Stats as(java.lang.String alias) {
		return new Stats(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Stats rename(java.lang.String name) {
		return new Stats(name, null);
	}
}
