/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.TournamentLBRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class TournamentLB extends org.jooq.impl.TableImpl<TournamentLBRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = -8859678;

	/**
	 * The reference instance of <code>Account.TournamentLB</code>
	 */
	public static final ehnetwork.database.tables.TournamentLB TournamentLB = new TournamentLB();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<TournamentLBRecord> getRecordType() {
		return TournamentLBRecord.class;
	}

	/**
	 * The column <code>Account.TournamentLB.rank</code>.
	 */
	public final org.jooq.TableField<TournamentLBRecord, org.jooq.types.UInteger> rank = createField("rank", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.TournamentLB.accountId</code>.
	 */
	public final org.jooq.TableField<TournamentLBRecord, org.jooq.types.UInteger> accountId = createField("accountId", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * The column <code>Account.TournamentLB.value</code>.
	 */
	public final org.jooq.TableField<TournamentLBRecord, org.jooq.types.UInteger> value = createField("value", org.jooq.impl.SQLDataType.INTEGERUNSIGNED.nullable(false), this, "");

	/**
	 * Create a <code>Account.TournamentLB</code> table reference
	 */
	public TournamentLB() {
		this("TournamentLB", null);
	}

	/**
	 * Create an aliased <code>Account.TournamentLB</code> table reference
	 */
	public TournamentLB(java.lang.String alias) {
		this(alias, ehnetwork.database.tables.TournamentLB.TournamentLB);
	}

	private TournamentLB(java.lang.String alias, org.jooq.Table<TournamentLBRecord> aliased) {
		this(alias, aliased, null);
	}

	private TournamentLB(java.lang.String alias, org.jooq.Table<TournamentLBRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<TournamentLBRecord> getPrimaryKey() {
		return Keys.KEY_TournamentLB_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<TournamentLBRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<TournamentLBRecord>>asList(Keys.KEY_TournamentLB_PRIMARY, Keys.KEY_TournamentLB_UK_PlayerEntry);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ehnetwork.database.tables.TournamentLB as(java.lang.String alias) {
		return new TournamentLB(alias, this);
	}

	/**
	 * Rename this table
	 */
	public ehnetwork.database.tables.TournamentLB rename(java.lang.String name) {
		return new TournamentLB(name, null);
	}
}
