/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables;

import ehnetwork.database.Account;
import ehnetwork.database.Keys;
import ehnetwork.database.tables.records.TransactionsRecord;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class Transactions extends org.jooq.impl.TableImpl<TransactionsRecord> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 513318870;

	/**
	 * The reference instance of <code>Account.transactions</code>
	 */
	public static final Transactions transactions = new Transactions();

	/**
	 * The class holding records for this type
	 */
	@Override
	public java.lang.Class<TransactionsRecord> getRecordType() {
		return TransactionsRecord.class;
	}

	/**
	 * The column <code>Account.transactions.id</code>.
	 */
	public final org.jooq.TableField<TransactionsRecord, java.lang.Integer> id = createField("id", org.jooq.impl.SQLDataType.INTEGER.nullable(false), this, "");

	/**
	 * The column <code>Account.transactions.name</code>.
	 */
	public final org.jooq.TableField<TransactionsRecord, java.lang.String> name = createField("name", org.jooq.impl.SQLDataType.VARCHAR.length(60).nullable(false), this, "");

	/**
	 * Create a <code>Account.transactions</code> table reference
	 */
	public Transactions() {
		this("transactions", null);
	}

	/**
	 * Create an aliased <code>Account.transactions</code> table reference
	 */
	public Transactions(java.lang.String alias) {
		this(alias, Transactions.transactions);
	}

	private Transactions(java.lang.String alias, org.jooq.Table<TransactionsRecord> aliased) {
		this(alias, aliased, null);
	}

	private Transactions(java.lang.String alias, org.jooq.Table<TransactionsRecord> aliased, org.jooq.Field<?>[] parameters) {
		super(alias, Account.Account, aliased, parameters, "");
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Identity<TransactionsRecord, java.lang.Integer> getIdentity() {
		return Keys.IDENTITY_transactions;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.UniqueKey<TransactionsRecord> getPrimaryKey() {
		return Keys.KEY_transactions_PRIMARY;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.util.List<org.jooq.UniqueKey<TransactionsRecord>> getKeys() {
		return java.util.Arrays.<org.jooq.UniqueKey<TransactionsRecord>>asList(Keys.KEY_transactions_PRIMARY);
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public Transactions as(java.lang.String alias) {
		return new Transactions(alias, this);
	}

	/**
	 * Rename this table
	 */
	public Transactions rename(java.lang.String name) {
		return new Transactions(name, null);
	}
}
