/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables.records;

import ehnetwork.database.tables.ClanTerritory;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class ClanTerritoryRecord extends org.jooq.impl.UpdatableRecordImpl<ClanTerritoryRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean> {

	private static final long serialVersionUID = 1422111385;

	/**
	 * Setter for <code>Account.clanTerritory.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.clanTerritory.clanId</code>.
	 */
	public void setClanId(java.lang.Integer value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.clanId</code>.
	 */
	public java.lang.Integer getClanId() {
		return (java.lang.Integer) getValue(1);
	}

	/**
	 * Setter for <code>Account.clanTerritory.serverId</code>.
	 */
	public void setServerId(java.lang.Integer value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.serverId</code>.
	 */
	public java.lang.Integer getServerId() {
		return (java.lang.Integer) getValue(2);
	}

	/**
	 * Setter for <code>Account.clanTerritory.chunk</code>.
	 */
	public void setChunk(java.lang.String value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.chunk</code>.
	 */
	public java.lang.String getChunk() {
		return (java.lang.String) getValue(3);
	}

	/**
	 * Setter for <code>Account.clanTerritory.safe</code>.
	 */
	public void setSafe(java.lang.Boolean value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.clanTerritory.safe</code>.
	 */
	public java.lang.Boolean getSafe() {
		return (java.lang.Boolean) getValue(4);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record5 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean> fieldsRow() {
		return (org.jooq.Row5) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row5<java.lang.Integer, java.lang.Integer, java.lang.Integer, java.lang.String, java.lang.Boolean> valuesRow() {
		return (org.jooq.Row5) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return ClanTerritory.clanTerritory.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field2() {
		return ClanTerritory.clanTerritory.clanId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field3() {
		return ClanTerritory.clanTerritory.serverId;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field4() {
		return ClanTerritory.clanTerritory.chunk;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Boolean> field5() {
		return ClanTerritory.clanTerritory.safe;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value2() {
		return getClanId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value3() {
		return getServerId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value4() {
		return getChunk();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Boolean value5() {
		return getSafe();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value2(java.lang.Integer value) {
		setClanId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value3(java.lang.Integer value) {
		setServerId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value4(java.lang.String value) {
		setChunk(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord value5(java.lang.Boolean value) {
		setSafe(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public ClanTerritoryRecord values(java.lang.Integer value1, java.lang.Integer value2, java.lang.Integer value3, java.lang.String value4, java.lang.Boolean value5) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached ClanTerritoryRecord
	 */
	public ClanTerritoryRecord() {
		super(ClanTerritory.clanTerritory);
	}

	/**
	 * Create a detached, initialised ClanTerritoryRecord
	 */
	public ClanTerritoryRecord(java.lang.Integer id, java.lang.Integer clanId, java.lang.Integer serverId, java.lang.String chunk, java.lang.Boolean safe) {
		super(ClanTerritory.clanTerritory);

		setValue(0, id);
		setValue(1, clanId);
		setValue(2, serverId);
		setValue(3, chunk);
		setValue(4, safe);
	}
}
