/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.tables.records;

import ehnetwork.database.tables.EloRating;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class EloRatingRecord extends org.jooq.impl.UpdatableRecordImpl<EloRatingRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record6<org.jooq.types.UInteger, java.lang.String, org.jooq.types.UByte, org.jooq.types.UInteger, java.lang.Integer, java.lang.String> {

	private static final long serialVersionUID = 329740739;

	/**
	 * Setter for <code>Account.eloRating.id</code>.
	 */
	public void setId(org.jooq.types.UInteger value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.eloRating.id</code>.
	 */
	public org.jooq.types.UInteger getId() {
		return (org.jooq.types.UInteger) getValue(0);
	}

	/**
	 * Setter for <code>Account.eloRating.uuid</code>.
	 */
	public void setUuid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.eloRating.uuid</code>.
	 */
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Account.eloRating.gamemode</code>.
	 */
	public void setGamemode(org.jooq.types.UByte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.eloRating.gamemode</code>.
	 */
	public org.jooq.types.UByte getGamemode() {
		return (org.jooq.types.UByte) getValue(2);
	}

	/**
	 * Setter for <code>Account.eloRating.matchesPlayed</code>.
	 */
	public void setMatchesPlayed(org.jooq.types.UInteger value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.eloRating.matchesPlayed</code>.
	 */
	public org.jooq.types.UInteger getMatchesPlayed() {
		return (org.jooq.types.UInteger) getValue(3);
	}

	/**
	 * Setter for <code>Account.eloRating.elo</code>.
	 */
	public void setElo(java.lang.Integer value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.eloRating.elo</code>.
	 */
	public java.lang.Integer getElo() {
		return (java.lang.Integer) getValue(4);
	}

	/**
	 * Setter for <code>Account.eloRating.gameType</code>.
	 */
	public void setGameType(java.lang.String value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.eloRating.gameType</code>.
	 */
	public java.lang.String getGameType() {
		return (java.lang.String) getValue(5);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<org.jooq.types.UInteger> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record6 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<org.jooq.types.UInteger, java.lang.String, org.jooq.types.UByte, org.jooq.types.UInteger, java.lang.Integer, java.lang.String> fieldsRow() {
		return (org.jooq.Row6) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row6<org.jooq.types.UInteger, java.lang.String, org.jooq.types.UByte, org.jooq.types.UInteger, java.lang.Integer, java.lang.String> valuesRow() {
		return (org.jooq.Row6) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field1() {
		return EloRating.eloRating.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return EloRating.eloRating.uuid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UByte> field3() {
		return EloRating.eloRating.gamemode;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<org.jooq.types.UInteger> field4() {
		return EloRating.eloRating.matchesPlayed;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field5() {
		return EloRating.eloRating.elo;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field6() {
		return EloRating.eloRating.gameType;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UByte value3() {
		return getGamemode();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.types.UInteger value4() {
		return getMatchesPlayed();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value5() {
		return getElo();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value6() {
		return getGameType();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord value1(org.jooq.types.UInteger value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord value2(java.lang.String value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord value3(org.jooq.types.UByte value) {
		setGamemode(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord value4(org.jooq.types.UInteger value) {
		setMatchesPlayed(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord value5(java.lang.Integer value) {
		setElo(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord value6(java.lang.String value) {
		setGameType(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public EloRatingRecord values(org.jooq.types.UInteger value1, java.lang.String value2, org.jooq.types.UByte value3, org.jooq.types.UInteger value4, java.lang.Integer value5, java.lang.String value6) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached EloRatingRecord
	 */
	public EloRatingRecord() {
		super(EloRating.eloRating);
	}

	/**
	 * Create a detached, initialised EloRatingRecord
	 */
	public EloRatingRecord(org.jooq.types.UInteger id, java.lang.String uuid, org.jooq.types.UByte gamemode, org.jooq.types.UInteger matchesPlayed, java.lang.Integer elo, java.lang.String gameType) {
		super(EloRating.eloRating);

		setValue(0, id);
		setValue(1, uuid);
		setValue(2, gamemode);
		setValue(3, matchesPlayed);
		setValue(4, elo);
		setValue(5, gameType);
	}
}
