/**
 * This class is generated by jOOQ
 */
package mineplex.database.tables.records;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class AccountPreferencesRecord extends org.jooq.impl.UpdatableRecordImpl<mineplex.database.tables.records.AccountPreferencesRecord> implements java.io.Serializable, java.lang.Cloneable, org.jooq.Record20<java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.String> {

	private static final long serialVersionUID = 296650044;

	/**
	 * Setter for <code>Account.accountPreferences.id</code>.
	 */
	public void setId(java.lang.Integer value) {
		setValue(0, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.id</code>.
	 */
	public java.lang.Integer getId() {
		return (java.lang.Integer) getValue(0);
	}

	/**
	 * Setter for <code>Account.accountPreferences.uuid</code>.
	 */
	public void setUuid(java.lang.String value) {
		setValue(1, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.uuid</code>.
	 */
	public java.lang.String getUuid() {
		return (java.lang.String) getValue(1);
	}

	/**
	 * Setter for <code>Account.accountPreferences.filterChat</code>.
	 */
	public void setFilterChat(java.lang.Byte value) {
		setValue(2, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.filterChat</code>.
	 */
	public java.lang.Byte getFilterChat() {
		return (java.lang.Byte) getValue(2);
	}

	/**
	 * Setter for <code>Account.accountPreferences.invisibility</code>.
	 */
	public void setInvisibility(java.lang.Byte value) {
		setValue(3, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.invisibility</code>.
	 */
	public java.lang.Byte getInvisibility() {
		return (java.lang.Byte) getValue(3);
	}

	/**
	 * Setter for <code>Account.accountPreferences.games</code>.
	 */
	public void setGames(java.lang.Byte value) {
		setValue(4, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.games</code>.
	 */
	public java.lang.Byte getGames() {
		return (java.lang.Byte) getValue(4);
	}

	/**
	 * Setter for <code>Account.accountPreferences.visibility</code>.
	 */
	public void setVisibility(java.lang.Byte value) {
		setValue(5, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.visibility</code>.
	 */
	public java.lang.Byte getVisibility() {
		return (java.lang.Byte) getValue(5);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendChat</code>.
	 */
	public void setFriendChat(java.lang.Byte value) {
		setValue(6, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendChat</code>.
	 */
	public java.lang.Byte getFriendChat() {
		return (java.lang.Byte) getValue(6);
	}

	/**
	 * Setter for <code>Account.accountPreferences.privateMessaging</code>.
	 */
	public void setPrivateMessaging(java.lang.Byte value) {
		setValue(7, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.privateMessaging</code>.
	 */
	public java.lang.Byte getPrivateMessaging() {
		return (java.lang.Byte) getValue(7);
	}

	/**
	 * Setter for <code>Account.accountPreferences.showChat</code>.
	 */
	public void setShowChat(java.lang.Byte value) {
		setValue(8, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.showChat</code>.
	 */
	public java.lang.Byte getShowChat() {
		return (java.lang.Byte) getValue(8);
	}

	/**
	 * Setter for <code>Account.accountPreferences.partyRequests</code>.
	 */
	public void setPartyRequests(java.lang.Byte value) {
		setValue(9, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.partyRequests</code>.
	 */
	public java.lang.Byte getPartyRequests() {
		return (java.lang.Byte) getValue(9);
	}

	/**
	 * Setter for <code>Account.accountPreferences.forcefield</code>.
	 */
	public void setForcefield(java.lang.Byte value) {
		setValue(10, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.forcefield</code>.
	 */
	public java.lang.Byte getForcefield() {
		return (java.lang.Byte) getValue(10);
	}

	/**
	 * Setter for <code>Account.accountPreferences.showMacReports</code>.
	 */
	public void setShowMacReports(java.lang.Byte value) {
		setValue(11, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.showMacReports</code>.
	 */
	public java.lang.Byte getShowMacReports() {
		return (java.lang.Byte) getValue(11);
	}

	/**
	 * Setter for <code>Account.accountPreferences.ignoreVelocity</code>.
	 */
	public void setIgnoreVelocity(java.lang.Byte value) {
		setValue(12, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.ignoreVelocity</code>.
	 */
	public java.lang.Byte getIgnoreVelocity() {
		return (java.lang.Byte) getValue(12);
	}

	/**
	 * Setter for <code>Account.accountPreferences.pendingFriendRequests</code>.
	 */
	public void setPendingFriendRequests(java.lang.Byte value) {
		setValue(13, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.pendingFriendRequests</code>.
	 */
	public java.lang.Byte getPendingFriendRequests() {
		return (java.lang.Byte) getValue(13);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendDisplayInventoryUI</code>.
	 */
	public void setFriendDisplayInventoryUI(java.lang.Byte value) {
		setValue(14, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendDisplayInventoryUI</code>.
	 */
	public java.lang.Byte getFriendDisplayInventoryUI() {
		return (java.lang.Byte) getValue(14);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendDisplayOnlineStatus</code>.
	 */
	public void setFriendDisplayOnlineStatus(java.lang.Byte value) {
		setValue(15, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendDisplayOnlineStatus</code>.
	 */
	public java.lang.Byte getFriendDisplayOnlineStatus() {
		return (java.lang.Byte) getValue(15);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendDisplayServerName</code>.
	 */
	public void setFriendDisplayServerName(java.lang.Byte value) {
		setValue(16, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendDisplayServerName</code>.
	 */
	public java.lang.Byte getFriendDisplayServerName() {
		return (java.lang.Byte) getValue(16);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendAllowRequests</code>.
	 */
	public void setFriendAllowRequests(java.lang.Byte value) {
		setValue(17, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendAllowRequests</code>.
	 */
	public java.lang.Byte getFriendAllowRequests() {
		return (java.lang.Byte) getValue(17);
	}

	/**
	 * Setter for <code>Account.accountPreferences.friendAllowMessaging</code>.
	 */
	public void setFriendAllowMessaging(java.lang.Byte value) {
		setValue(18, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.friendAllowMessaging</code>.
	 */
	public java.lang.Byte getFriendAllowMessaging() {
		return (java.lang.Byte) getValue(18);
	}

	/**
	 * Setter for <code>Account.accountPreferences.language</code>.
	 */
	public void setLanguage(java.lang.String value) {
		setValue(19, value);
	}

	/**
	 * Getter for <code>Account.accountPreferences.language</code>.
	 */
	public java.lang.String getLanguage() {
		return (java.lang.String) getValue(19);
	}

	// -------------------------------------------------------------------------
	// Primary key information
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Record1<java.lang.Integer> key() {
		return (org.jooq.Record1) super.key();
	}

	// -------------------------------------------------------------------------
	// Record20 type implementation
	// -------------------------------------------------------------------------

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.String> fieldsRow() {
		return (org.jooq.Row20) super.fieldsRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Row20<java.lang.Integer, java.lang.String, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.Byte, java.lang.String> valuesRow() {
		return (org.jooq.Row20) super.valuesRow();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Integer> field1() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.id;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field2() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.uuid;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field3() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.filterChat;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field4() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.invisibility;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field5() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.games;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field6() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.visibility;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field7() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.friendChat;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field8() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.privateMessaging;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field9() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.showChat;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field10() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.partyRequests;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field11() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.forcefield;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field12() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.showMacReports;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field13() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.ignoreVelocity;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field14() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.pendingFriendRequests;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field15() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.friendDisplayInventoryUI;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field16() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.friendDisplayOnlineStatus;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field17() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.friendDisplayServerName;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field18() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.friendAllowRequests;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.Byte> field19() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.friendAllowMessaging;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public org.jooq.Field<java.lang.String> field20() {
		return mineplex.database.tables.AccountPreferences.accountPreferences.language;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Integer value1() {
		return getId();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value2() {
		return getUuid();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value3() {
		return getFilterChat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value4() {
		return getInvisibility();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value5() {
		return getGames();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value6() {
		return getVisibility();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value7() {
		return getFriendChat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value8() {
		return getPrivateMessaging();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value9() {
		return getShowChat();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value10() {
		return getPartyRequests();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value11() {
		return getForcefield();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value12() {
		return getShowMacReports();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value13() {
		return getIgnoreVelocity();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value14() {
		return getPendingFriendRequests();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value15() {
		return getFriendDisplayInventoryUI();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value16() {
		return getFriendDisplayOnlineStatus();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value17() {
		return getFriendDisplayServerName();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value18() {
		return getFriendAllowRequests();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.Byte value19() {
		return getFriendAllowMessaging();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public java.lang.String value20() {
		return getLanguage();
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value1(java.lang.Integer value) {
		setId(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value2(java.lang.String value) {
		setUuid(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value3(java.lang.Byte value) {
		setFilterChat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value4(java.lang.Byte value) {
		setInvisibility(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value5(java.lang.Byte value) {
		setGames(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value6(java.lang.Byte value) {
		setVisibility(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value7(java.lang.Byte value) {
		setFriendChat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value8(java.lang.Byte value) {
		setPrivateMessaging(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value9(java.lang.Byte value) {
		setShowChat(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value10(java.lang.Byte value) {
		setPartyRequests(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value11(java.lang.Byte value) {
		setForcefield(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value12(java.lang.Byte value) {
		setShowMacReports(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value13(java.lang.Byte value) {
		setIgnoreVelocity(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value14(java.lang.Byte value) {
		setPendingFriendRequests(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value15(java.lang.Byte value) {
		setFriendDisplayInventoryUI(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value16(java.lang.Byte value) {
		setFriendDisplayOnlineStatus(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value17(java.lang.Byte value) {
		setFriendDisplayServerName(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value18(java.lang.Byte value) {
		setFriendAllowRequests(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value19(java.lang.Byte value) {
		setFriendAllowMessaging(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord value20(java.lang.String value) {
		setLanguage(value);
		return this;
	}

	/**
	 * {@inheritDoc}
	 */
	@Override
	public AccountPreferencesRecord values(java.lang.Integer value1, java.lang.String value2, java.lang.Byte value3, java.lang.Byte value4, java.lang.Byte value5, java.lang.Byte value6, java.lang.Byte value7, java.lang.Byte value8, java.lang.Byte value9, java.lang.Byte value10, java.lang.Byte value11, java.lang.Byte value12, java.lang.Byte value13, java.lang.Byte value14, java.lang.Byte value15, java.lang.Byte value16, java.lang.Byte value17, java.lang.Byte value18, java.lang.Byte value19, java.lang.String value20) {
		return this;
	}

	// -------------------------------------------------------------------------
	// Constructors
	// -------------------------------------------------------------------------

	/**
	 * Create a detached AccountPreferencesRecord
	 */
	public AccountPreferencesRecord() {
		super(mineplex.database.tables.AccountPreferences.accountPreferences);
	}

	/**
	 * Create a detached, initialised AccountPreferencesRecord
	 */
	public AccountPreferencesRecord(java.lang.Integer id, java.lang.String uuid, java.lang.Byte filterChat, java.lang.Byte invisibility, java.lang.Byte games, java.lang.Byte visibility, java.lang.Byte friendChat, java.lang.Byte privateMessaging, java.lang.Byte showChat, java.lang.Byte partyRequests, java.lang.Byte forcefield, java.lang.Byte showMacReports, java.lang.Byte ignoreVelocity, java.lang.Byte pendingFriendRequests, java.lang.Byte friendDisplayInventoryUI, java.lang.Byte friendDisplayOnlineStatus, java.lang.Byte friendDisplayServerName, java.lang.Byte friendAllowRequests, java.lang.Byte friendAllowMessaging, java.lang.String language) {
		super(mineplex.database.tables.AccountPreferences.accountPreferences);

		setValue(0, id);
		setValue(1, uuid);
		setValue(2, filterChat);
		setValue(3, invisibility);
		setValue(4, games);
		setValue(5, visibility);
		setValue(6, friendChat);
		setValue(7, privateMessaging);
		setValue(8, showChat);
		setValue(9, partyRequests);
		setValue(10, forcefield);
		setValue(11, showMacReports);
		setValue(12, ignoreVelocity);
		setValue(13, pendingFriendRequests);
		setValue(14, friendDisplayInventoryUI);
		setValue(15, friendDisplayOnlineStatus);
		setValue(16, friendDisplayServerName);
		setValue(17, friendAllowRequests);
		setValue(18, friendAllowMessaging);
		setValue(19, language);
	}
}
