package com.neustar.ultra.api.webservice.v01;

import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.xml.ws.WebEndpoint;
import javax.xml.ws.WebServiceClient;
import javax.xml.ws.WebServiceFeature;
import javax.xml.ws.Service;

/**
 * This class was generated by Apache CXF 2.7.7
 * 2014-01-15T10:08:40.739-05:00
 * Generated source version: 2.7.7
 * 
 */
@WebServiceClient(name = "UltraWebServiceV01Service", 
                  wsdlLocation = "http://ultra-api.ultradns.com/UltraDNS_WS/v01?wsdl",
                  targetNamespace = "http://webservice.api.ultra.neustar.com/v01/") 
public class UltraWebServiceV01Service extends Service {

    public final static URL WSDL_LOCATION;

    public final static QName SERVICE = new QName("http://webservice.api.ultra.neustar.com/v01/", "UltraWebServiceV01Service");
    public final static QName UltraWebServiceV01Port = new QName("http://webservice.api.ultra.neustar.com/v01/", "UltraWebServiceV01Port");
    static {
        URL url = null;
        try {
            url = new URL("http://ultra-api.ultradns.com/UltraDNS_WS/v01?wsdl");
        } catch (MalformedURLException e) {
            java.util.logging.Logger.getLogger(UltraWebServiceV01Service.class.getName())
                .log(java.util.logging.Level.INFO, 
                     "Can not initialize the default wsdl from {0}", "http://ultra-api.ultradns.com/UltraDNS_WS/v01?wsdl");
        }
        WSDL_LOCATION = url;
    }

    public UltraWebServiceV01Service(URL wsdlLocation) {
        super(wsdlLocation, SERVICE);
    }

    public UltraWebServiceV01Service(URL wsdlLocation, QName serviceName) {
        super(wsdlLocation, serviceName);
    }

    public UltraWebServiceV01Service() {
        super(WSDL_LOCATION, SERVICE);
    }
    

    /**
     *
     * @return
     *     returns UltraDNS1
     */
    @WebEndpoint(name = "UltraWebServiceV01Port")
    public UltraDNS1 getUltraWebServiceV01Port() {
        return super.getPort(UltraWebServiceV01Port, UltraDNS1.class);
    }

    /**
     * 
     * @param features
     *     A list of {@link javax.xml.ws.WebServiceFeature} to configure on the proxy.  Supported features not in the <code>features</code> parameter will have their default values.
     * @return
     *     returns UltraDNS1
     */
    @WebEndpoint(name = "UltraWebServiceV01Port")
    public UltraDNS1 getUltraWebServiceV01Port(WebServiceFeature... features) {
        return super.getPort(UltraWebServiceV01Port, UltraDNS1.class, features);
    }

}
