/**
 * This class is generated by jOOQ
 */
package ehnetwork.database.routines;

import ehnetwork.database.Account;

/**
 * This class is generated by jOOQ.
 */
@javax.annotation.Generated(
	value = {
		"http://www.jooq.org",
		"jOOQ version:3.5.2"
	},
	comments = "This class is generated by jOOQ"
)
@java.lang.SuppressWarnings({ "all", "unchecked", "rawtypes" })
public class PlayerLogin extends org.jooq.impl.AbstractRoutine<java.lang.Void> implements java.io.Serializable, java.lang.Cloneable {

	private static final long serialVersionUID = 442861619;

	/**
	 * The parameter <code>Account.playerLogin.paramUuid</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> paramUuid = createParameter("paramUuid", org.jooq.impl.SQLDataType.VARCHAR.length(100), false);

	/**
	 * The parameter <code>Account.playerLogin.paramName</code>.
	 */
	public static final org.jooq.Parameter<java.lang.String> paramName = createParameter("paramName", org.jooq.impl.SQLDataType.VARCHAR.length(100), false);

	/**
	 * Create a new routine call instance
	 */
	public PlayerLogin() {
		super("playerLogin", Account.Account);

		addInParameter(paramUuid);
		addInParameter(paramName);
	}

	/**
	 * Set the <code>paramUuid</code> parameter IN value to the routine
	 */
	public void setParamUuid(java.lang.String value) {
		setValue(PlayerLogin.paramUuid, value);
	}

	/**
	 * Set the <code>paramName</code> parameter IN value to the routine
	 */
	public void setParamName(java.lang.String value) {
		setValue(PlayerLogin.paramName, value);
	}
}
